/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 外部导入客户批次信息表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PltExtImportBatch extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1339850723;

	/**
	 * The singleton instance of ccms.plt_ext_import_batch
	 */
	public static final com.yunat.ccms.jooq.tables.PltExtImportBatch PLT_EXT_IMPORT_BATCH = new com.yunat.ccms.jooq.tables.PltExtImportBatch();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.plt_ext_import_batch.batch_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> BATCH_ID = createField("batch_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 导入批次名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> BATCH_NAME = createField("batch_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 导入客户所属平台的平台代码，与uni_plat.plat_code关联
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PLAT_CODE = createField("plat_code", org.jooq.impl.SQLDataType.CHAR, this);

	/**
	 * 文件名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> FILE_NAME = createField("file_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 起始行
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> START_LINE = createField("start_line", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * 对应内部文件名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> INTERNAL_FILE_NAME = createField("internal_file_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.plt_ext_import_batch.has_column_name</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> HAS_COLUMN_NAME = createField("has_column_name", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * 分隔符
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SPLIT_CHAR = createField("split_char", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 导入数据的表名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> IMPORT_TABLE_NAME = createField("import_table_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 成功记录数
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> SUCCESS_RECORD = createField("success_record", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * 总记录数
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> TOTAL_RECORD = createField("total_record", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>ccms.plt_ext_import_batch.has_clear</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> HAS_CLEAR = createField("has_clear", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The table column <code>ccms.plt_ext_import_batch.has_imported</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> HAS_IMPORTED = createField("has_imported", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * 创建时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 清除时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CLEARED = createField("cleared", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 批次创建人的系统用户名，与tb_sysuser.username关联
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CREATOR = createField("creator", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 批次清除人的系统用户名，与tb_sysuser.username关联
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CLEANER = createField("cleaner", org.jooq.impl.SQLDataType.VARCHAR, this);

	public PltExtImportBatch() {
		super("plt_ext_import_batch", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public PltExtImportBatch(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.PltExtImportBatch.PLT_EXT_IMPORT_BATCH);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_PLT_EXT_IMPORT_BATCH;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_PLT_EXT_IMPORT_BATCH_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_PLT_EXT_IMPORT_BATCH_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.PltExtImportBatch as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.PltExtImportBatch(alias);
	}
}
