/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PltExtBatchCustomer extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -1871743180;

	/**
	 * The singleton instance of ccms.plt_ext_batch_customer
	 */
	public static final com.yunat.ccms.jooq.tables.PltExtBatchCustomer PLT_EXT_BATCH_CUSTOMER = new com.yunat.ccms.jooq.tables.PltExtBatchCustomer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 导入批次ID
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> BATCH_ID = createField("batch_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * 平台代码
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PLAT_CODE = createField("plat_code", org.jooq.impl.SQLDataType.CHAR, this);

	/**
	 * 客户所属平台的客户ID
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CUSTOMERNO = createField("customerno", org.jooq.impl.SQLDataType.VARCHAR, this);

	public PltExtBatchCustomer() {
		super("plt_ext_batch_customer", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public PltExtBatchCustomer(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.PltExtBatchCustomer.PLT_EXT_BATCH_CUSTOMER);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_PLT_EXT_BATCH_CUSTOMER_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_PLT_EXT_BATCH_CUSTOMER_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.PltExtBatchCustomer as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.PltExtBatchCustomer(alias);
	}
}
