/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * “客服工作台”客户标签数据表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PltKfgztCustomerLabel extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1544793351;

	/**
	 * The singleton instance of ccms.plt_kfgzt_customer_label
	 */
	public static final com.yunat.ccms.jooq.tables.PltKfgztCustomerLabel PLT_KFGZT_CUSTOMER_LABEL = new com.yunat.ccms.jooq.tables.PltKfgztCustomerLabel();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 店铺名（卖家昵称）
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SHOP_NAME = createField("shop_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 客户id
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CUSTOMERNO = createField("customerno", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 标签名称
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> LABEL_NAME = createField("label_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	public PltKfgztCustomerLabel() {
		super("plt_kfgzt_customer_label", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public PltKfgztCustomerLabel(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.PltKfgztCustomerLabel.PLT_KFGZT_CUSTOMER_LABEL);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_PLT_KFGZT_CUSTOMER_LABEL_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_PLT_KFGZT_CUSTOMER_LABEL_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.PltKfgztCustomerLabel as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.PltKfgztCustomerLabel(alias);
	}
}
