/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * “客服工作台”店铺签字典表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PltKfgztShopLabel extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -1339565020;

	/**
	 * The singleton instance of ccms.plt_kfgzt_shop_label
	 */
	public static final com.yunat.ccms.jooq.tables.PltKfgztShopLabel PLT_KFGZT_SHOP_LABEL = new com.yunat.ccms.jooq.tables.PltKfgztShopLabel();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 店铺名（卖家昵称）
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SHOP_NAME = createField("shop_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 自然主键
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> LABEL_ID = createField("label_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 标签名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> LABEL_NAME = createField("label_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 解释
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> LABEL_EXPLAIN = createField("label_explain", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 创建时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> LABEL_TIME = createField("label_time", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 父节点id(lable_id)
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> LABEL_PARENT_ID = createField("label_parent_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.plt_kfgzt_shop_label.is_parent</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> IS_PARENT = createField("is_parent", org.jooq.impl.SQLDataType.TINYINT, this);

	public PltKfgztShopLabel() {
		super("plt_kfgzt_shop_label", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public PltKfgztShopLabel(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.PltKfgztShopLabel.PLT_KFGZT_SHOP_LABEL);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_PLT_KFGZT_SHOP_LABEL_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_PLT_KFGZT_SHOP_LABEL_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.PltKfgztShopLabel as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.PltKfgztShopLabel(alias);
	}
}
