/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * “客服工作台”同步客户信息
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PltKfgztCustomer extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1087115031;

	/**
	 * The singleton instance of ccms.plt_kfgzt_customer
	 */
	public static final com.yunat.ccms.jooq.tables.PltKfgztCustomer PLT_KFGZT_CUSTOMER = new com.yunat.ccms.jooq.tables.PltKfgztCustomer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 客户ID
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CUSTOMERNO = createField("customerno", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 姓名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> FULL_NAME = createField("full_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 性别
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SEX = createField("sex", org.jooq.impl.SQLDataType.CHAR, this);

	/**
	 * 职业
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> JOB = createField("job", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 出生年份
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Short> BIRTH_YEAR = createField("birth_year", org.jooq.impl.SQLDataType.SMALLINT, this);

	/**
	 * 生日
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Date> BIRTHDAY = createField("birthday", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * 邮箱
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 手机号码
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> MOBILE = createField("mobile", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 座机号码
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 邮编
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> ZIP = createField("zip", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 国家
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> COUNTRY = createField("country", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 省份
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 城市（地级）
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 区县（县级）
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DISTRICT = createField("district", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 地址
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 客户属性变更时间（仅限统一客户信息表uni_customer中包含的属性）
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CHANGED = createField("changed", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	public PltKfgztCustomer() {
		super("plt_kfgzt_customer", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public PltKfgztCustomer(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.PltKfgztCustomer.PLT_KFGZT_CUSTOMER);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_PLT_KFGZT_CUSTOMER_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_PLT_KFGZT_CUSTOMER_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.PltKfgztCustomer as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.PltKfgztCustomer(alias);
	}
}
