/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 手工修改的统一客户信息表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PltModifyCustomerLog extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -922293615;

	/**
	 * The singleton instance of ccms.plt_modify_customer_log
	 */
	public static final com.yunat.ccms.jooq.tables.PltModifyCustomerLog PLT_MODIFY_CUSTOMER_LOG = new com.yunat.ccms.jooq.tables.PltModifyCustomerLog();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.plt_modify_customer_log.log_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> LOG_ID = createField("log_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 客户ID, 手工修改的客户ID值与其uni_customer.uni_id一致
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CUSTOMERNO = createField("customerno", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 手工修改客户属性的数据库字段名, 可手工修改的字段名包括：full_name, sex, job, birth_year, birthday, email, mobile, phone, zip, country, state, city, district, address
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> COLUMN_NAME = createField("column_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 修改前字段值
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> BEFOR = createField("befor", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 修改后字段值
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> AFTER = createField("after", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 系统用户名，逻辑关联 tb_sysuser.username
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SYSUSER_NAME = createField("sysuser_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 手工修改时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	public PltModifyCustomerLog() {
		super("plt_modify_customer_log", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public PltModifyCustomerLog(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.PltModifyCustomerLog.PLT_MODIFY_CUSTOMER_LOG);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_PLT_MODIFY_CUSTOMER_LOG;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_PLT_MODIFY_CUSTOMER_LOG_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_PLT_MODIFY_CUSTOMER_LOG_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.PltModifyCustomerLog as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.PltModifyCustomerLog(alias);
	}
}
