/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 商品对应的商品属性
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PltTaobaoProductProp extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 2090651320;

	/**
	 * The singleton instance of ccms.plt_taobao_product_prop
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoProductProp PLT_TAOBAO_PRODUCT_PROP = new com.yunat.ccms.jooq.tables.PltTaobaoProductProp();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 商品ID
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> NUM_IID = createField("num_iid", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 属性ID
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PID = createField("pid", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 属性名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PROP_NAME = createField("prop_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 属性值ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> VID = createField("vid", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 属性值名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 属性值别名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> NAME_ALIAS = createField("name_alias", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.plt_taobao_product_prop.is_input_prop</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> IS_INPUT_PROP = createField("is_input_prop", org.jooq.impl.SQLDataType.TINYINT, this);

	public PltTaobaoProductProp() {
		super("plt_taobao_product_prop", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public PltTaobaoProductProp(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.PltTaobaoProductProp.PLT_TAOBAO_PRODUCT_PROP);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_PRODUCT_PROP_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_PRODUCT_PROP_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.PltTaobaoProductProp as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.PltTaobaoProductProp(alias);
	}
}
