/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 商品属性
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PltTaobaoItemProp extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -239847151;

	/**
	 * The singleton instance of ccms.plt_taobao_item_prop
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoItemProp PLT_TAOBAO_ITEM_PROP = new com.yunat.ccms.jooq.tables.PltTaobaoItemProp();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 属性 ID 例：品牌的PID=20000
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PID = createField("pid", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 上级属性ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PARENT_PID = createField("parent_pid", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 上级属性值ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PARENT_VID = createField("parent_vid", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 属性名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.plt_taobao_item_prop.is_input_prop</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> IS_INPUT_PROP = createField("is_input_prop", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The table column <code>ccms.plt_taobao_item_prop.is_key_prop</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> IS_KEY_PROP = createField("is_key_prop", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The table column <code>ccms.plt_taobao_item_prop.is_sale_prop</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> IS_SALE_PROP = createField("is_sale_prop", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The table column <code>ccms.plt_taobao_item_prop.is_color_prop</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> IS_COLOR_PROP = createField("is_color_prop", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The table column <code>ccms.plt_taobao_item_prop.is_enum_prop</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> IS_ENUM_PROP = createField("is_enum_prop", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The table column <code>ccms.plt_taobao_item_prop.is_item_prop</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> IS_ITEM_PROP = createField("is_item_prop", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The table column <code>ccms.plt_taobao_item_prop.must</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> MUST = createField("must", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The table column <code>ccms.plt_taobao_item_prop.multi</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> MULTI = createField("multi", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * 状态。可选值:normal(正常),deleted(删除)
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 排列序号。取值范围:大于零的整排列序号。取值范围:大于零的整数
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> SORT_ORDER = createField("sort_order", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>ccms.plt_taobao_item_prop.child_template</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CHILD_TEMPLATE = createField("child_template", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.plt_taobao_item_prop.is_allow_alias</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> IS_ALLOW_ALIAS = createField("is_allow_alias", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * 店铺ID，当属性为店铺自定义属性时（is_input_prop=true）有值，否则为Null
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DP_ID = createField("dp_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	public PltTaobaoItemProp() {
		super("plt_taobao_item_prop", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public PltTaobaoItemProp(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.PltTaobaoItemProp.PLT_TAOBAO_ITEM_PROP);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_ITEM_PROP_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_ITEM_PROP_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.PltTaobaoItemProp as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.PltTaobaoItemProp(alias);
	}
}
