/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 商品对应的卖家自定义类目
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PltTaobaoProductSellerCat extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -1149178896;

	/**
	 * The singleton instance of ccms.plt_taobao_product_seller_cat
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoProductSellerCat PLT_TAOBAO_PRODUCT_SELLER_CAT = new com.yunat.ccms.jooq.tables.PltTaobaoProductSellerCat();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 商品编号
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> NUM_IID = createField("num_iid", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 卖家自定义类目编号
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SELLER_CID = createField("seller_cid", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 卖家自定义类目名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 店铺类目类型：可选值：manual_type：手动分类，new_type：新品上价， tree_type：二三级类目树 ，property_type：属性叶子类目树， brand_type：品牌推广
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR, this);

	public PltTaobaoProductSellerCat() {
		super("plt_taobao_product_seller_cat", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public PltTaobaoProductSellerCat(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.PltTaobaoProductSellerCat.PLT_TAOBAO_PRODUCT_SELLER_CAT);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_PRODUCT_SELLER_CAT_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_PRODUCT_SELLER_CAT_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.PltTaobaoProductSellerCat as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.PltTaobaoProductSellerCat(alias);
	}
}
