/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 淘宝店铺信息表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PltTaobaoShop extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -687471595;

	/**
	 * The singleton instance of ccms.plt_taobao_shop
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoShop PLT_TAOBAO_SHOP = new com.yunat.ccms.jooq.tables.PltTaobaoShop();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 店铺ID
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SHOP_ID = createField("shop_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 店铺名称，即店主用户昵称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SHOP_NAME = createField("shop_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 店铺类型，B天猫店，C淘宝店
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SHOP_TYPE = createField("shop_type", org.jooq.impl.SQLDataType.CHAR, this);

	/**
	 * The table column <code>ccms.plt_taobao_shop.order_created_earliest</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> ORDER_CREATED_EARLIEST = createField("order_created_earliest", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The table column <code>ccms.plt_taobao_shop.order_created_latest</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> ORDER_CREATED_LATEST = createField("order_created_latest", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The table column <code>ccms.plt_taobao_shop.acookie_visit_date</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Date> ACOOKIE_VISIT_DATE = createField("acookie_visit_date", org.jooq.impl.SQLDataType.DATE, this);

	public PltTaobaoShop() {
		super("plt_taobao_shop", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public PltTaobaoShop(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.PltTaobaoShop.PLT_TAOBAO_SHOP);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_SHOP_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_SHOP_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.PltTaobaoShop as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.PltTaobaoShop(alias);
	}
}
