/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 订单表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PltTaobaoOrder extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1238800583;

	/**
	 * The singleton instance of ccms.plt_taobao_order
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoOrder PLT_TAOBAO_ORDER = new com.yunat.ccms.jooq.tables.PltTaobaoOrder();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 订单号
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TID = createField("tid", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 店铺ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DP_ID = createField("dp_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 客户ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CUSTOMERNO = createField("customerno", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 交易创建时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 交易结束时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> ENDTIME = createField("endtime", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 交易状态,TRADE_NO_CREATE_PAY(没创建支付宝交易),WAIT_BUYER_PAY,WAIT_SELLER_SEND_GOODS,WAIT_BUYER_CONFIRM_GOODS,TRADE_BUYER_SIGNED(买家已签收,货到付款专用),TRADE_FINISHED,TRADE_CLOSED(付款以后用户退款成功，交易自动关闭),TRADE_CLOSED_BY_TAOBAO
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 交易来源。 WAP(手机);HITAO(嗨淘);TOP(TOP平台);TAOBAO(普通淘宝);JHS(聚划算)
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TRADE_FROM = createField("trade_from", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 交易类型列表，同时查询多种交易类型可用逗号分隔。默认同时查询guarantee_trade, auto_delivery, ec, cod的4种交易类型的数据 可选值 fixed一口价 auction拍卖 guarantee_trade一口价、拍卖 auto_delivery自动发货 independent_simple_trade旺店入门版交易 independent_shop_trade旺店标准版交易 ec直冲 cod货到付款 fenxiao分销 game_equipment游戏装备...
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 付款时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> PAY_TIME = createField("pay_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 商品金额
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> TOTAL_FEE = createField("total_fee", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * 邮费
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> POST_FEE = createField("post_fee", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * 卖家发货时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CONSIGN_TIME = createField("consign_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The table column <code>ccms.plt_taobao_order.ccms_order_status</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Short> CCMS_ORDER_STATUS = createField("ccms_order_status", org.jooq.impl.SQLDataType.SMALLINT, this);

	/**
	 * 订单修改时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 支付宝交易号，如：2009112081173831
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> ALIPAY_NO = createField("alipay_no", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 实付金额。精确到2位小数;单位:元。如:200.07，表示:200元7分
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> PAYMENT = createField("payment", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * 系统优惠金额（如打折，VIP，满就送等），精确到2位小数，单位：元。如：200.07，表示：200元7分
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> DISCOUNT_FEE = createField("discount_fee", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * 买家使用积分。格式:100;单位:个.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> POINT_FEE = createField("point_fee", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * 买家实际使用积分（扣除部分退款使用的积分）。格式:100;单位:个
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> REAL_POINT_FEE = createField("real_point_fee", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * 创建交易时的物流方式（交易完成前，物流方式有可能改变，但系统里的这个字段一直不变）。可选值：ems, express, post, free, virtual。
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SHIPPING_TYPE = createField("shipping_type", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 买家货到付款服务费。精确到2位小数;单位:元。如:12.07，表示:12元7分
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> BUYER_COD_FEE = createField("buyer_cod_fee", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * 卖家货到付款服务费。精确到2位小数;单位:元。如:12.07，表示:12元7分。卖家不承担服务费的订单：未发货的订单获取服务费为0，发货后就能获取到正确值。
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> SELLER_COD_FEE = createField("seller_cod_fee", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * 快递代收款。精确到2位小数;单位:元。如:212.07，表示:212元7分
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> EXPRESS_AGENCY_FEE = createField("express_agency_fee", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * 卖家手工调整金额，精确到2位小数，单位：元。如：200.07，表示：200元7分。来源于订单价格修改，如果有多笔子订单的时候，这个为0，单笔的话则跟[order].adjust_fee一样
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> ADJUST_FEE = createField("adjust_fee", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * 买家获得积分,返点的积分。格式:100;单位:个。返点的积分要交易成功之后才能获得。
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> BUYER_OBTAIN_POINT_FEE = createField("buyer_obtain_point_fee", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * 货到付款服务费。精确到2位小数;单位:元。如:12.07，表示:12元7分。
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> COD_FEE = createField("cod_fee", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * 货到付款物流状态。 初始状态 NEW_CREATED,接单成功 CANCELED,接单失败 REJECTED_BY_COMPANY,接单超时 RECIEVE_TIMEOUT,揽收成功 TAKEN_IN_SUCCESS,揽收失败 TAKEN_IN_FAILED,揽收超时 RECIEVE_TIMEOUT,签收成功 SIGN_IN,签收失败 REJECTED_BY_OTHER_SIDE,订单等待发送给物流公司 WAITING_TO_BE_SENT,用户取消物流订单 CANCELED
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> COD_STATUS = createField("cod_status", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 买家支付宝账号
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> BUYER_ALIPAY_NO = createField("buyer_alipay_no", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 收货人的姓名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> RECEIVER_NAME = createField("receiver_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 收货人的所在省份
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> RECEIVER_STATE = createField("receiver_state", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 收货人的所在城市
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> RECEIVER_CITY = createField("receiver_city", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 收货人的所在地区
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> RECEIVER_DISTRICT = createField("receiver_district", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 收货人的详细地址
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> RECEIVER_ADDRESS = createField("receiver_address", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 收货人的邮编
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> RECEIVER_ZIP = createField("receiver_zip", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 收货人的手机号码
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> RECEIVER_MOBILE = createField("receiver_mobile", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 收货人的电话号码
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> RECEIVER_PHONE = createField("receiver_phone", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 买家邮件地址
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> BUYER_EMAIL = createField("buyer_email", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 交易佣金。精确到2位小数;单位:元。如:200.07，表示:200元7分
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> COMMISSION_FEE = createField("commission_fee", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * 子订单的退款金额合计
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> REFUND_FEE = createField("refund_fee", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * 商品数量总计
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> NUM = createField("num", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * 卖家实际收到的支付宝打款金额（由于子订单可以部分确认收货，这个金额会随着子订单的确认收货而不断增加，交易成功后等于买家实付款减去退款金额）。精确到2位小数;单位:元。如:200.07，表示:200元7分
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> RECEIVED_PAYMENT = createField("received_payment", org.jooq.impl.SQLDataType.DECIMAL, this);

	public PltTaobaoOrder() {
		super("plt_taobao_order", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public PltTaobaoOrder(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.PltTaobaoOrder.PLT_TAOBAO_ORDER);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_ORDER_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_ORDER_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.PltTaobaoOrder as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.PltTaobaoOrder(alias);
	}
}
