/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 淘宝商品表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PltTaobaoProduct extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -1457627428;

	/**
	 * The singleton instance of ccms.plt_taobao_product
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoProduct PLT_TAOBAO_PRODUCT = new com.yunat.ccms.jooq.tables.PltTaobaoProduct();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 商品数字ID
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> NUM_IID = createField("num_iid", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 商品URL
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DETAIL_URL = createField("detail_url", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 商品标题，商品名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * Item的发布时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 非分销商品：0，代销：1，经销：2
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> IS_FENXIAO = createField("is_fenxiao", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 商品所属的叶子类目 id
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> CID = createField("cid", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 商品图片地址
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PIC_URL = createField("pic_url", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 商品上架时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> LIST_TIME = createField("list_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 下架时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> DELIST_TIME = createField("delist_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The table column <code>ccms.plt_taobao_product.price</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> PRICE = createField("price", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * 修改时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 商品上传后的状态。onsale出售中，instock库中
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> APPROVE_STATUS = createField("approve_status", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 店铺ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DP_ID = createField("dp_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 商家外部编码
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> OUTER_ID = createField("outer_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	public PltTaobaoProduct() {
		super("plt_taobao_product", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public PltTaobaoProduct(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.PltTaobaoProduct.PLT_TAOBAO_PRODUCT);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_PRODUCT_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_PRODUCT_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.PltTaobaoProduct as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.PltTaobaoProduct(alias);
	}
}
