/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 商品类目
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PltTaobaoItemCat extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -756937429;

	/**
	 * The singleton instance of ccms.plt_taobao_item_cat
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoItemCat PLT_TAOBAO_ITEM_CAT = new com.yunat.ccms.jooq.tables.PltTaobaoItemCat();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 商品所属类目ID
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CID = createField("cid", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 父类目ID=0时，代表的是一级的类目
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PARENT_CID = createField("parent_cid", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 类目名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.plt_taobao_item_cat.is_parent</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> IS_PARENT = createField("is_parent", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * 状态。可选值:normal(正常),deleted(删除)
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 排列序号，表示同级类目的展现次序，如数值相等则按名称次序排列。取值范围:大于零的整数
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> SORT_ORDER = createField("sort_order", org.jooq.impl.SQLDataType.INTEGER, this);

	public PltTaobaoItemCat() {
		super("plt_taobao_item_cat", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public PltTaobaoItemCat(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.PltTaobaoItemCat.PLT_TAOBAO_ITEM_CAT);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_ITEM_CAT_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_ITEM_CAT_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.PltTaobaoItemCat as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.PltTaobaoItemCat(alias);
	}
}
