/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 淘宝优惠券信息表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PltTaobaoCoupon extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 627983153;

	/**
	 * The singleton instance of ccms.plt_taobao_coupon
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoCoupon PLT_TAOBAO_COUPON = new com.yunat.ccms.jooq.tables.PltTaobaoCoupon();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.plt_taobao_coupon.coupon_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> COUPON_ID = createField("coupon_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 优惠券名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> COUPON_NAME = createField("coupon_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 店铺
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SHOP_ID = createField("shop_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 创建时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED_TIME = createField("created_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 生效日期
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 截止日期
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> END_TIME = createField("end_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 优惠券消费门槛(元)
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> THRESHOLD = createField("threshold", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * 面额
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Short> DENOMINATION_VALUE = createField("denomination_value", org.jooq.impl.SQLDataType.SMALLINT, this);

	/**
	 * The table column <code>ccms.plt_taobao_coupon.creator</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> CREATOR = createField("creator", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * 优惠券是否启动
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> ENABLE = createField("enable", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * 备注
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR, this);

	public PltTaobaoCoupon() {
		super("plt_taobao_coupon", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public PltTaobaoCoupon(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.PltTaobaoCoupon.PLT_TAOBAO_COUPON);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_COUPON_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_COUPON_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.PltTaobaoCoupon as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.PltTaobaoCoupon(alias);
	}
}
