/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 淘宝物流运单
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PltTaobaoShipping extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1301220432;

	/**
	 * The singleton instance of ccms.plt_taobao_shipping
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoShipping PLT_TAOBAO_SHIPPING = new com.yunat.ccms.jooq.tables.PltTaobaoShipping();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 物流订单编号
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> ORDER_CODE = createField("order_code", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 交易ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TID = createField("tid", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 店铺ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DP_ID = createField("dp_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.plt_taobao_shipping.is_quick_cod_order</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> IS_QUICK_COD_ORDER = createField("is_quick_cod_order", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * 卖家昵称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SELLER_NICK = createField("seller_nick", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 买家昵称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> BUYER_NICK = createField("buyer_nick", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 预约取货结束时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> DELIVERY_END = createField("delivery_end", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 预约取货开始时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> DELIVERY_START = createField("delivery_start", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 运单号.具体一个物流公司的运单号码.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> OUT_SID = createField("out_sid", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 货物名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> ITEM_TITLE = createField("item_title", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 收件人手机号码
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> RECEIVER_MOBILE = createField("receiver_mobile", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 收件人姓名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> RECEIVER_NAME = createField("receiver_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 收件人电话
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> RECEIVER_PHONE = createField("receiver_phone", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 物流订单状态,CREATED(已创建) RECREATED(重新创建) CANCELLED(订单已取消) CLOSED(订单关闭) SENDING(等候发送给物流公司) ACCEPTING(已发送给物流公司,等待接单) ACCEPTED(物流公司已接单) REJECTED(物流公司不接单) PICK_UP(物流公司揽收成功) PICK_UP_FAILED(物流公司揽收失败) LOST(物流公司丢单) REJECTED_BY_RECEIVER(拒签) ACCEPTED_BY_RECEIVER(已签收)
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.CHAR, this);

	/**
	 * 物流方式.可选值:free(卖家包邮),post(平邮),express(快递),ems(EMS).
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.CHAR, this);

	/**
	 * 谁承担运费.可选值:buyer(买家承担),seller(卖家承担运费).
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> FREIGHT_PAYER = createField("freight_payer", org.jooq.impl.SQLDataType.CHAR, this);

	/**
	 * The table column <code>ccms.plt_taobao_shipping.seller_confirm</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> SELLER_CONFIRM = createField("seller_confirm", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * 物流公司名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> COMPANY_NAME = createField("company_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.plt_taobao_shipping.is_success</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> IS_SUCCESS = createField("is_success", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * 运单创建时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 运单修改时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	public PltTaobaoShipping() {
		super("plt_taobao_shipping", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public PltTaobaoShipping(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.PltTaobaoShipping.PLT_TAOBAO_SHIPPING);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_SHIPPING_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_SHIPPING_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.PltTaobaoShipping as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.PltTaobaoShipping(alias);
	}
}
