/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 淘宝优惠券面额字典表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PltTaobaoCouponDenomination extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 402652988;

	/**
	 * The singleton instance of ccms.plt_taobao_coupon_denomination
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoCouponDenomination PLT_TAOBAO_COUPON_DENOMINATION = new com.yunat.ccms.jooq.tables.PltTaobaoCouponDenomination();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 面额名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DENOMINATION_NAME = createField("denomination_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 面额值
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Short> DENOMINATION_VALUE = createField("denomination_value", org.jooq.impl.SQLDataType.SMALLINT, this);

	public PltTaobaoCouponDenomination() {
		super("plt_taobao_coupon_denomination", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public PltTaobaoCouponDenomination(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.PltTaobaoCouponDenomination.PLT_TAOBAO_COUPON_DENOMINATION);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_COUPON_DENOMINATION_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_COUPON_DENOMINATION_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.PltTaobaoCouponDenomination as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.PltTaobaoCouponDenomination(alias);
	}
}
