/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 零售版支付类型的数据字典表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PltTaobaoPayType extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 58503572;

	/**
	 * The singleton instance of ccms.plt_taobao_pay_type
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoPayType PLT_TAOBAO_PAY_TYPE = new com.yunat.ccms.jooq.tables.PltTaobaoPayType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.plt_taobao_pay_type.pay_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> PAY_ID = createField("pay_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 支付类型
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PAY_TYPE = createField("pay_type", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 备注
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PAY_TYPE_DESC = createField("pay_type_desc", org.jooq.impl.SQLDataType.VARCHAR, this);

	public PltTaobaoPayType() {
		super("plt_taobao_pay_type", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public PltTaobaoPayType(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.PltTaobaoPayType.PLT_TAOBAO_PAY_TYPE);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_PAY_TYPE_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_PLT_TAOBAO_PAY_TYPE_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.PltTaobaoPayType as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.PltTaobaoPayType(alias);
	}
}
