/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * “我的中心”店铺邮件订阅用户表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PltWdzxEmailSubscribe extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1649574376;

	/**
	 * The singleton instance of ccms.plt_wdzx_email_subscribe
	 */
	public static final com.yunat.ccms.jooq.tables.PltWdzxEmailSubscribe PLT_WDZX_EMAIL_SUBSCRIBE = new com.yunat.ccms.jooq.tables.PltWdzxEmailSubscribe();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 店铺id
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DP_ID = createField("dp_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 用户昵称
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CUSTOMERNO = createField("customerno", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 订阅邮箱
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 订阅时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> DINGYUE_DATE = createField("dingyue_date", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	public PltWdzxEmailSubscribe() {
		super("plt_wdzx_email_subscribe", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public PltWdzxEmailSubscribe(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.PltWdzxEmailSubscribe.PLT_WDZX_EMAIL_SUBSCRIBE);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_PLT_WDZX_EMAIL_SUBSCRIBE_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_PLT_WDZX_EMAIL_SUBSCRIBE_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.PltWdzxEmailSubscribe as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.PltWdzxEmailSubscribe(alias);
	}
}
