/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 应用级属性参数配置表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TbAppProperties extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 2067845490;

	/**
	 * The singleton instance of ccms.tb_app_properties
	 */
	public static final com.yunat.ccms.jooq.tables.TbAppProperties TB_APP_PROPERTIES = new com.yunat.ccms.jooq.tables.TbAppProperties();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 参数ID,仅作主键,不应该被其他表应用
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> PROP_ID = createField("prop_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 参数所属组别,取值：FTP、MQ、CHANNEL、CCMS
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PROP_GROUP = createField("prop_group", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 配置参数名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PROP_NAME = createField("prop_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 配置值
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PROP_VALUE = createField("prop_value", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 描述
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PROP_DESC = createField("prop_desc", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TbAppProperties() {
		super("tb_app_properties", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TbAppProperties(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TbAppProperties.TB_APP_PROPERTIES);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TB_APP_PROPERTIES;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TB_APP_PROPERTIES_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TB_APP_PROPERTIES_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TbAppProperties as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TbAppProperties(alias);
	}
}
