/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 应用订购期
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TbAppExpired extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1663056838;

	/**
	 * The singleton instance of ccms.tb_app_expired
	 */
	public static final com.yunat.ccms.jooq.tables.TbAppExpired TB_APP_EXPIRED = new com.yunat.ccms.jooq.tables.TbAppExpired();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * rmi用户名
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> ASSOCIATE_USERNAME = createField("associate_username", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 淘宝应用订购过期时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Date> EXPIRE_DATE = createField("expire_date", org.jooq.impl.SQLDataType.DATE, this);

	public TbAppExpired() {
		super("tb_app_expired", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TbAppExpired(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TbAppExpired.TB_APP_EXPIRED);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TB_APP_EXPIRED_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TB_APP_EXPIRED_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TbAppExpired as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TbAppExpired(alias);
	}
}
