/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 活动的基本信息表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TbCampaign extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -1218822722;

	/**
	 * The singleton instance of ccms.tb_campaign
	 */
	public static final com.yunat.ccms.jooq.tables.TbCampaign TB_CAMPAIGN = new com.yunat.ccms.jooq.tables.TbCampaign();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tb_campaign.camp_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> CAMP_ID = createField("camp_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.tb_campaign.prog_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> PROG_ID = createField("prog_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 活动的名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CAMP_NAME = createField("camp_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 客户自定义活动类别，对应tdu_campaign_type主键
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> CAMP_TYPE = createField("camp_type", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * 活动的状态,对应的字典表td_camp_status
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CAMP_STATUS = createField("camp_status", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.tb_campaign.creater</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> CREATER = createField("creater", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>ccms.tb_campaign.investigator</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> INVESTIGATOR = createField("investigator", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * 创建时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED_TIME = createField("created_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 开始时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 结束时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> END_TIME = createField("end_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 描述
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CAMP_DESC = createField("camp_desc", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 备注
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> COMMENTS = createField("comments", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 流程id
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> WORKFLOW_ID = createField("workflow_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 活动所属流程类别; STANDARD：标准，RFM：RFM，CUSTOM_INDEX：自定义标签，MEMBER_MANAGE：会员管理
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> WORKFLOW_TYPE = createField("workflow_type", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 平台代码
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PLAT_CODE = createField("plat_code", org.jooq.impl.SQLDataType.CHAR, this);

	/**
	 * 版本Edition
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> EDITION = createField("edition", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 流程图片地址
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PIC_URL = createField("pic_url", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.tb_campaign.disabled</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> DISABLED = createField("disabled", org.jooq.impl.SQLDataType.TINYINT, this);

	public TbCampaign() {
		super("tb_campaign", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TbCampaign(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TbCampaign.TB_CAMPAIGN);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TB_CAMPAIGN;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TB_CAMPAIGN_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TB_CAMPAIGN_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TbCampaign as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TbCampaign(alias);
	}
}
