/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 活动的审批的备注
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TbCampInvestigateComments extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -1099067566;

	/**
	 * The singleton instance of ccms.tb_camp_investigate_comments
	 */
	public static final com.yunat.ccms.jooq.tables.TbCampInvestigateComments TB_CAMP_INVESTIGATE_COMMENTS = new com.yunat.ccms.jooq.tables.TbCampInvestigateComments();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tb_camp_investigate_comments.comments_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> COMMENTS_ID = createField("comments_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.tb_camp_investigate_comments.camp_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> CAMP_ID = createField("camp_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 备注创建的时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATE_DATE = createField("create_date", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 备注的内容
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> COMMENTS = createField("comments", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.tb_camp_investigate_comments.operator</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> OPERATOR = createField("operator", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * 审批的操作。如：提交审批，通过审批，拒绝审批
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> OPERATION = createField("operation", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TbCampInvestigateComments() {
		super("tb_camp_investigate_comments", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TbCampInvestigateComments(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TbCampInvestigateComments.TB_CAMP_INVESTIGATE_COMMENTS);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TB_CAMP_INVESTIGATE_COMMENTS;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TB_CAMP_INVESTIGATE_COMMENTS_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TB_CAMP_INVESTIGATE_COMMENTS_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TbCampInvestigateComments as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TbCampInvestigateComments(alias);
	}
}
