/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 沟通项目表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TbProgram extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -185447363;

	/**
	 * The singleton instance of ccms.tb_program
	 */
	public static final com.yunat.ccms.jooq.tables.TbProgram TB_PROGRAM = new com.yunat.ccms.jooq.tables.TbProgram();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tb_program.prog_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> PROG_ID = createField("prog_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 项目名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PROG_NAME = createField("prog_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.tb_program.type</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>ccms.tb_program.creator</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> CREATOR = createField("creator", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * 创建时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED_TIME = createField("created_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 开始时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 结束时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> END_TIME = createField("end_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 项目描述
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PROG_DESC = createField("prog_desc", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 备注
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> COMMENTS = createField("comments", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 平台代码
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PLAT_CODE = createField("plat_code", org.jooq.impl.SQLDataType.CHAR, this);

	/**
	 * 版本Edition
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> EDITION = createField("edition", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TbProgram() {
		super("tb_program", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TbProgram(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TbProgram.TB_PROGRAM);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TB_PROGRAM;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TB_PROGRAM_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TB_PROGRAM_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TbProgram as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TbProgram(alias);
	}
}
