/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 访问异常日志表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TbRemoteLogException extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1732861582;

	/**
	 * The singleton instance of ccms.tb_remote_log_exception
	 */
	public static final com.yunat.ccms.jooq.tables.TbRemoteLogException TB_REMOTE_LOG_EXCEPTION = new com.yunat.ccms.jooq.tables.TbRemoteLogException();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tb_remote_log_exception.exception_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> EXCEPTION_ID = createField("exception_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 操作用户ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 触发函数名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> FUNCTION_NAME = createField("function_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 异常信息描述
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> EXCEPTION_DESC = createField("exception_desc", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * 生成时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	public TbRemoteLogException() {
		super("tb_remote_log_exception", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TbRemoteLogException(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TbRemoteLogException.TB_REMOTE_LOG_EXCEPTION);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TB_REMOTE_LOG_EXCEPTION;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TB_REMOTE_LOG_EXCEPTION_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TB_REMOTE_LOG_EXCEPTION_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TbRemoteLogException as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TbRemoteLogException(alias);
	}
}
