/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 系统用户角色表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TbRole extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 142835295;

	/**
	 * The singleton instance of ccms.tb_role
	 */
	public static final com.yunat.ccms.jooq.tables.TbRole TB_ROLE = new com.yunat.ccms.jooq.tables.TbRole();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tb_role.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.tb_role.name</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.tb_role.memo</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> MEMO = createField("memo", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TbRole() {
		super("tb_role", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TbRole(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TbRole.TB_ROLE);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TB_ROLE;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TB_ROLE_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TB_ROLE_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TbRole as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TbRole(alias);
	}
}
