/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 系统用户角色－权限关系表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TbRolePermission extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -315441356;

	/**
	 * The singleton instance of ccms.tb_role_permission
	 */
	public static final com.yunat.ccms.jooq.tables.TbRolePermission TB_ROLE_PERMISSION = new com.yunat.ccms.jooq.tables.TbRolePermission();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tb_role_permission.role_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.tb_role_permission.permission_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> PERMISSION_ID = createField("permission_id", org.jooq.impl.SQLDataType.BIGINT, this);

	public TbRolePermission() {
		super("tb_role_permission", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TbRolePermission(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TbRolePermission.TB_ROLE_PERMISSION);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TB_ROLE_PERMISSION_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TB_ROLE_PERMISSION_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TbRolePermission as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TbRolePermission(alias);
	}
}
