/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 系统用户表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TbSysuser extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1861065721;

	/**
	 * The singleton instance of ccms.tb_sysuser
	 */
	public static final com.yunat.ccms.jooq.tables.TbSysuser TB_SYSUSER = new com.yunat.ccms.jooq.tables.TbSysuser();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tb_sysuser.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 用户类型
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> USER_TYPE = createField("user_type", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 用户登录名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> LOGIN_NAME = createField("login_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 用户登录密码
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 用户真实姓名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> REAL_NAME = createField("real_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 用户手机号码
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> MOBILE = createField("mobile", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.tb_sysuser.email</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.tb_sysuser.disabled</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DISABLED = createField("disabled", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 用户创建时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	public TbSysuser() {
		super("tb_sysuser", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TbSysuser(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TbSysuser.TB_SYSUSER);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TB_SYSUSER;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TB_SYSUSER_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TB_SYSUSER_PRIMARY, com.yunat.ccms.jooq.Keys.KEY_TB_SYSUSER_UK_TB_SYSUSER_LOGINNAME_USERTYPE);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TbSysuser as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TbSysuser(alias);
	}
}
