/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 活动模板表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TbTemplate extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -1217058078;

	/**
	 * The singleton instance of ccms.tb_template
	 */
	public static final com.yunat.ccms.jooq.tables.TbTemplate TB_TEMPLATE = new com.yunat.ccms.jooq.tables.TbTemplate();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tb_template.template_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> TEMPLATE_ID = createField("template_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 模板名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TEMPLATE_NAME = createField("template_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 创建人
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> CREATOR = createField("creator", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * 创建时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED_TIME = createField("created_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 修改时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> UPDATED_TIME = createField("updated_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 描述
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TEMPLATE_DESC = createField("template_desc", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 备注
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> COMMENTS = createField("comments", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 流程id
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> WORKFLOW_ID = createField("workflow_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 平台代码
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PLAT_CODE = createField("plat_code", org.jooq.impl.SQLDataType.CHAR, this);

	/**
	 * 版本Edition
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> EDITION = createField("edition", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 流程图片地址
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PIC_URL = createField("pic_url", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 模版状态(1:生效、0:失效)
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> DISABLED = createField("disabled", org.jooq.impl.SQLDataType.TINYINT, this);

	public TbTemplate() {
		super("tb_template", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TbTemplate(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TbTemplate.TB_TEMPLATE);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TB_TEMPLATE;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TB_TEMPLATE_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TB_TEMPLATE_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TbTemplate as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TbTemplate(alias);
	}
}
