/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 任务状态维表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TdsJobStatus extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 645558946;

	/**
	 * The singleton instance of ccms.tds_job_status
	 */
	public static final com.yunat.ccms.jooq.tables.TdsJobStatus TDS_JOB_STATUS = new com.yunat.ccms.jooq.tables.TdsJobStatus();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tds_job_status.status_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> STATUS_ID = createField("status_id", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The table column <code>ccms.tds_job_status.status_name</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> STATUS_NAME = createField("status_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TdsJobStatus() {
		super("tds_job_status", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TdsJobStatus(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TdsJobStatus.TDS_JOB_STATUS);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TDS_JOB_STATUS_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TDS_JOB_STATUS_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TdsJobStatus as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TdsJobStatus(alias);
	}
}
