/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * CCMS订单状态维表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TdsOrderStatus extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -2050611127;

	/**
	 * The singleton instance of ccms.tds_order_status
	 */
	public static final com.yunat.ccms.jooq.tables.TdsOrderStatus TDS_ORDER_STATUS = new com.yunat.ccms.jooq.tables.TdsOrderStatus();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tds_order_status.status_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Short> STATUS_ID = createField("status_id", org.jooq.impl.SQLDataType.SMALLINT, this);

	/**
	 * The table column <code>ccms.tds_order_status.status_value</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> STATUS_VALUE = createField("status_value", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.tds_order_status.status_name</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> STATUS_NAME = createField("status_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.tds_order_status.orderid</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Short> ORDERID = createField("orderid", org.jooq.impl.SQLDataType.SMALLINT, this);

	public TdsOrderStatus() {
		super("tds_order_status", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TdsOrderStatus(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TdsOrderStatus.TDS_ORDER_STATUS);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TDS_ORDER_STATUS_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TDS_ORDER_STATUS_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TdsOrderStatus as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TdsOrderStatus(alias);
	}
}
