/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TdsPermission extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -41528356;

	/**
	 * The singleton instance of ccms.tds_permission
	 */
	public static final com.yunat.ccms.jooq.tables.TdsPermission TDS_PERMISSION = new com.yunat.ccms.jooq.tables.TdsPermission();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tds_permission.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.tds_permission.name</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.tds_permission.memo</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> MEMO = createField("memo", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.tds_permission.permission_key</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PERMISSION_KEY = createField("permission_key", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TdsPermission() {
		super("tds_permission", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TdsPermission(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TdsPermission.TDS_PERMISSION);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TDS_PERMISSION;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TDS_PERMISSION_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TDS_PERMISSION_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TdsPermission as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TdsPermission(alias);
	}
}
