/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 活动类型表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TduCampaignCategory extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 873337395;

	/**
	 * The singleton instance of ccms.tdu_campaign_category
	 */
	public static final com.yunat.ccms.jooq.tables.TduCampaignCategory TDU_CAMPAIGN_CATEGORY = new com.yunat.ccms.jooq.tables.TduCampaignCategory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tdu_campaign_category.category_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 活动类型名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CATEGORY_VALUE = createField("category_value", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.tdu_campaign_category.disabled</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> DISABLED = createField("disabled", org.jooq.impl.SQLDataType.TINYINT, this);

	public TduCampaignCategory() {
		super("tdu_campaign_category", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TduCampaignCategory(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TduCampaignCategory.TDU_CAMPAIGN_CATEGORY);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TDU_CAMPAIGN_CATEGORY_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TDU_CAMPAIGN_CATEGORY_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TduCampaignCategory as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TduCampaignCategory(alias);
	}
}
