/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 项目类型字典表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TduProgType extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 704501877;

	/**
	 * The singleton instance of ccms.tdu_prog_type
	 */
	public static final com.yunat.ccms.jooq.tables.TduProgType TDU_PROG_TYPE = new com.yunat.ccms.jooq.tables.TduProgType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tdu_prog_type.prog_type_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> PROG_TYPE_ID = createField("prog_type_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 项目类型名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PROG_TYPE = createField("prog_type", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.tdu_prog_type.disabled</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> DISABLED = createField("disabled", org.jooq.impl.SQLDataType.TINYINT, this);

	public TduProgType() {
		super("tdu_prog_type", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TduProgType(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TduProgType.TDU_PROG_TYPE);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TDU_PROG_TYPE;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TDU_PROG_TYPE_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TDU_PROG_TYPE_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TduProgType as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TduProgType(alias);
	}
}
