/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 查询索引：原来的tm_view_dir表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TmCatalog extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1479155274;

	/**
	 * The singleton instance of ccms.tm_catalog
	 */
	public static final com.yunat.ccms.jooq.tables.TmCatalog TM_CATALOG = new com.yunat.ccms.jooq.tables.TmCatalog();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tm_catalog.catalog_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> CATALOG_ID = createField("catalog_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 索引分类
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Short> CATALOG_TYPE = createField("catalog_type", org.jooq.impl.SQLDataType.SMALLINT, this);

	/**
	 * 上级ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> PARENT_ID = createField("parent_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 显示名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SHOW_NAME = createField("show_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 显示顺序
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Short> SHOW_ORDER = createField("show_order", org.jooq.impl.SQLDataType.SMALLINT, this);

	/**
	 * 平台
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PLAT_CODE = createField("plat_code", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TmCatalog() {
		super("tm_catalog", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TmCatalog(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TmCatalog.TM_CATALOG);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TM_CATALOG;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TM_CATALOG_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TM_CATALOG_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TmCatalog as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TmCatalog(alias);
	}
}
