/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 索引和查询属性的多对多关联，可以重新定义显示名称和显示顺序
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TmCatalogCriteria extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -337397891;

	/**
	 * The singleton instance of ccms.tm_catalog_criteria
	 */
	public static final com.yunat.ccms.jooq.tables.TmCatalogCriteria TM_CATALOG_CRITERIA = new com.yunat.ccms.jooq.tables.TmCatalogCriteria();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tm_catalog_criteria.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 索引ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> CATALOG_ID = createField("catalog_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 查询属性ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> QUERY_CRITERIA_ID = createField("query_criteria_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 显示名称，覆盖数据字段定义，可空
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SHOW_NAME = createField("show_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 显示顺序，覆盖数据字段定义，可空
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Short> SHOW_ORDER = createField("show_order", org.jooq.impl.SQLDataType.SMALLINT, this);

	public TmCatalogCriteria() {
		super("tm_catalog_criteria", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TmCatalogCriteria(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TmCatalogCriteria.TM_CATALOG_CRITERIA);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TM_CATALOG_CRITERIA;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TM_CATALOG_CRITERIA_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TM_CATALOG_CRITERIA_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TmCatalogCriteria as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TmCatalogCriteria(alias);
	}
}
