/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 物理表定义
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TmDbTable extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -1464213961;

	/**
	 * The singleton instance of ccms.tm_db_table
	 */
	public static final com.yunat.ccms.jooq.tables.TmDbTable TM_DB_TABLE = new com.yunat.ccms.jooq.tables.TmDbTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tm_db_table.table_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> TABLE_ID = createField("table_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 数据库表名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DB_NAME = createField("db_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 显示名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SHOW_NAME = createField("show_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 主键字段
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PK_COLUMN = createField("pk_column", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 平台代码
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PLAT_CODE = createField("plat_code", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 创建时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 更新时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 备注
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TmDbTable() {
		super("tm_db_table", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TmDbTable(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TmDbTable.TM_DB_TABLE);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TM_DB_TABLE;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TM_DB_TABLE_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TM_DB_TABLE_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TmDbTable as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TmDbTable(alias);
	}
}
