/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 物理表字段定义
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TmDbColumn extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1746821973;

	/**
	 * The singleton instance of ccms.tm_db_column
	 */
	public static final com.yunat.ccms.jooq.tables.TmDbColumn TM_DB_COLUMN = new com.yunat.ccms.jooq.tables.TmDbColumn();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tm_db_column.column_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> COLUMN_ID = createField("column_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.tm_db_column.table_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> TABLE_ID = createField("table_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.tm_db_column.dic_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> DIC_ID = createField("dic_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.tm_db_column.refer_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> REFER_ID = createField("refer_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 数据库字段名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DB_NAME = createField("db_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 显示名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SHOW_NAME = createField("show_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 数据库字段类型
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DB_TYPE = createField("db_type", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 是否主键
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> IS_PK = createField("is_pk", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * 创建时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 更新时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 备注
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TmDbColumn() {
		super("tm_db_column", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TmDbColumn(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TmDbColumn.TM_DB_COLUMN);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TM_DB_COLUMN;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TM_DB_COLUMN_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TM_DB_COLUMN_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TmDbColumn as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TmDbColumn(alias);
	}
}
