/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 字典类型枚举值表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TmDicValue extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1171741784;

	/**
	 * The singleton instance of ccms.tm_dic_value
	 */
	public static final com.yunat.ccms.jooq.tables.TmDicValue TM_DIC_VALUE = new com.yunat.ccms.jooq.tables.TmDicValue();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tm_dic_value.dic_value_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> DIC_VALUE_ID = createField("dic_value_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 字典表ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> DIC_ID = createField("dic_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 上级字典值的ID，构造树结构
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> PARENT_ID = createField("parent_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 实际值
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DIC_VALUE = createField("dic_value", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 显示名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SHOW_NAME = createField("show_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.tm_dic_value.remark</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TmDicValue() {
		super("tm_dic_value", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TmDicValue(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TmDicValue.TM_DIC_VALUE);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TM_DIC_VALUE;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TM_DIC_VALUE_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TM_DIC_VALUE_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TmDicValue as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TmDicValue(alias);
	}
}
