/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 查询模版的字段
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TmQueryColumn extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -1432165852;

	/**
	 * The singleton instance of ccms.tm_query_column
	 */
	public static final com.yunat.ccms.jooq.tables.TmQueryColumn TM_QUERY_COLUMN = new com.yunat.ccms.jooq.tables.TmQueryColumn();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tm_query_column.query_column_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> QUERY_COLUMN_ID = createField("query_column_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.tm_query_column.column_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> COLUMN_ID = createField("column_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.tm_query_column.query_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> QUERY_ID = createField("query_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.tm_query_column.query_table_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> QUERY_TABLE_ID = createField("query_table_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 显示表达式或者解析表达式
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> COLUMN_EXPR = createField("column_expr", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 显示名称或者匹配名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> COLUMN_NAME = createField("column_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 显示顺序
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Short> COLUMN_ORDER = createField("column_order", org.jooq.impl.SQLDataType.SMALLINT, this);

	public TmQueryColumn() {
		super("tm_query_column", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TmQueryColumn(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TmQueryColumn.TM_QUERY_COLUMN);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TM_QUERY_COLUMN;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TM_QUERY_COLUMN_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TM_QUERY_COLUMN_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TmQueryColumn as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TmQueryColumn(alias);
	}
}
