/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 查询模版包含的查询表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TmQueryTable extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 124863420;

	/**
	 * The singleton instance of ccms.tm_query_table
	 */
	public static final com.yunat.ccms.jooq.tables.TmQueryTable TM_QUERY_TABLE = new com.yunat.ccms.jooq.tables.TmQueryTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tm_query_table.query_table_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> QUERY_TABLE_ID = createField("query_table_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 查询模版ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> QUERY_ID = createField("query_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 表定义ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> TABLE_ID = createField("table_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 是否主表
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> IS_MASTER = createField("is_master", org.jooq.impl.SQLDataType.TINYINT, this);

	public TmQueryTable() {
		super("tm_query_table", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TmQueryTable(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TmQueryTable.TM_QUERY_TABLE);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TM_QUERY_TABLE;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TM_QUERY_TABLE_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TM_QUERY_TABLE_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TmQueryTable as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TmQueryTable(alias);
	}
}
