/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 查询属性
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TmQueryCriteria extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -1312979805;

	/**
	 * The singleton instance of ccms.tm_query_criteria
	 */
	public static final com.yunat.ccms.jooq.tables.TmQueryCriteria TM_QUERY_CRITERIA = new com.yunat.ccms.jooq.tables.TmQueryCriteria();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tm_query_criteria.query_criteria_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> QUERY_CRITERIA_ID = createField("query_criteria_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 查询模版ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> QUERY_ID = createField("query_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 字段ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> COLUMN_ID = createField("column_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 查询类型
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> QUERY_TYPE = createField("query_type", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 指标类型
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> QUOTA_TYPE = createField("quota_type", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 属性扩展表达式
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> COLUMN_EXPR = createField("column_expr", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TmQueryCriteria() {
		super("tm_query_criteria", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TmQueryCriteria(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TmQueryCriteria.TM_QUERY_CRITERIA);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TM_QUERY_CRITERIA;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TM_QUERY_CRITERIA_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TM_QUERY_CRITERIA_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TmQueryCriteria as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TmQueryCriteria(alias);
	}
}
