/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 查询where部分定义，也包含groupby 和 having
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TmQueryJoinCriteria extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1801553557;

	/**
	 * The singleton instance of ccms.tm_query_join_criteria
	 */
	public static final com.yunat.ccms.jooq.tables.TmQueryJoinCriteria TM_QUERY_JOIN_CRITERIA = new com.yunat.ccms.jooq.tables.TmQueryJoinCriteria();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tm_query_join_criteria.query_join_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> QUERY_JOIN_ID = createField("query_join_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.tm_query_join_criteria.query_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> QUERY_ID = createField("query_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 左表关联字段
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> LEFT_COLUMN_ID = createField("left_column_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 右表关联字段
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> RIGHT_COLUMN_ID = createField("right_column_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 关联类型 inner left right
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> JOIN_TYPE = createField("join_type", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TmQueryJoinCriteria() {
		super("tm_query_join_criteria", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TmQueryJoinCriteria(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TmQueryJoinCriteria.TM_QUERY_JOIN_CRITERIA);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TM_QUERY_JOIN_CRITERIA;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TM_QUERY_JOIN_CRITERIA_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TM_QUERY_JOIN_CRITERIA_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TmQueryJoinCriteria as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TmQueryJoinCriteria(alias);
	}
}
