/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 关联类型的字典
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TmRefer extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1051605087;

	/**
	 * The singleton instance of ccms.tm_refer
	 */
	public static final com.yunat.ccms.jooq.tables.TmRefer TM_REFER = new com.yunat.ccms.jooq.tables.TmRefer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.tm_refer.refer_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> REFER_ID = createField("refer_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 平台代码
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PLAT_CODE = createField("plat_code", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 字典值
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> REFER_KEY = createField("refer_key", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 字典名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> REFER_NAME = createField("refer_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 来源表
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> REFER_TABLE = createField("refer_table", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 过滤条件
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> REFER_CRITERIA_SQL = createField("refer_criteria_sql", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 显示顺序
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> ORDER_COLUMN = createField("order_column", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 备注
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TmRefer() {
		super("tm_refer", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TmRefer(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TmRefer.TM_REFER);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TM_REFER;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TM_REFER_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TM_REFER_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TmRefer as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TmRefer(alias);
	}
}
