/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 活动执行总表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfLogJob extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 532999253;

	/**
	 * The singleton instance of ccms.twf_log_job
	 */
	public static final com.yunat.ccms.jooq.tables.TwfLogJob TWF_LOG_JOB = new com.yunat.ccms.jooq.tables.TwfLogJob();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.twf_log_job.job_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> JOB_ID = createField("job_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.twf_log_job.camp_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> CAMP_ID = createField("camp_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 状态，见表td_job_status
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Short> STATUS = createField("status", org.jooq.impl.SQLDataType.SMALLINT, this);

	/**
	 * 开始时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> STARTTIME = createField("starttime", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 结束时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> ENDTIME = createField("endtime", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The table column <code>ccms.twf_log_job.is_test</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> IS_TEST = createField("is_test", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The table column <code>ccms.twf_log_job.plantime</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> PLANTIME = createField("plantime", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The table column <code>ccms.twf_log_job.last_job</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> LAST_JOB = createField("last_job", org.jooq.impl.SQLDataType.TINYINT, this);

	public TwfLogJob() {
		super("twf_log_job", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfLogJob(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfLogJob.TWF_LOG_JOB);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TWF_LOG_JOB;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TWF_LOG_JOB_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TWF_LOG_JOB_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfLogJob as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfLogJob(alias);
	}
}
