/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 活动执行用户组用户 (subjob_id每隔10000就建立一个新的分区)
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfLogGroupUser extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1339746532;

	/**
	 * The singleton instance of ccms.twf_log_group_user
	 */
	public static final com.yunat.ccms.jooq.tables.TwfLogGroupUser TWF_LOG_GROUP_USER = new com.yunat.ccms.jooq.tables.TwfLogGroupUser();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.twf_log_group_user.subjob_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> SUBJOB_ID = createField("subjob_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 统一客户ID
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> UNI_ID = createField("uni_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 发送控制组类型，见td_control_group_type
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> CONTROL_GROUP_TYPE = createField("control_group_type", org.jooq.impl.SQLDataType.INTEGER, this);

	public TwfLogGroupUser() {
		super("twf_log_group_user", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfLogGroupUser(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfLogGroupUser.TWF_LOG_GROUP_USER);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TWF_LOG_GROUP_USER_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TWF_LOG_GROUP_USER_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfLogGroupUser as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfLogGroupUser(alias);
	}
}
