/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 用户渠道沟通日志表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfLogChannelUser extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -1087937293;

	/**
	 * The singleton instance of ccms.twf_log_channel_user
	 */
	public static final com.yunat.ccms.jooq.tables.TwfLogChannelUser TWF_LOG_CHANNEL_USER = new com.yunat.ccms.jooq.tables.TwfLogChannelUser();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 统一客户ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> UNI_ID = createField("uni_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 创建时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATETIME = createField("createtime", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The table column <code>ccms.twf_log_channel_user.subjob_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> SUBJOB_ID = createField("subjob_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 渠道执行状态（对应渠道反馈维表）
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Short> STATUS = createField("status", org.jooq.impl.SQLDataType.SMALLINT, this);

	/**
	 * 序列号
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> SERIAL_ID = createField("serial_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.twf_log_channel_user.node_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> NODE_ID = createField("node_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 用户在特定渠道上的联系信息，渠道为短信，记录手机号；渠道为EDM时，记录Email地址；
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> USER_CHANNEL_INFO = createField("user_channel_info", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TwfLogChannelUser() {
		super("twf_log_channel_user", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfLogChannelUser(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfLogChannelUser.TWF_LOG_CHANNEL_USER);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfLogChannelUser as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfLogChannelUser(alias);
	}
}
