/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 流程执行子任务表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfLogSubjob extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -1141497793;

	/**
	 * The singleton instance of ccms.twf_log_subjob
	 */
	public static final com.yunat.ccms.jooq.tables.TwfLogSubjob TWF_LOG_SUBJOB = new com.yunat.ccms.jooq.tables.TwfLogSubjob();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.twf_log_subjob.subjob_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> SUBJOB_ID = createField("subjob_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.twf_log_subjob.job_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> JOB_ID = createField("job_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.twf_log_subjob.camp_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> CAMP_ID = createField("camp_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.twf_log_subjob.node_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> NODE_ID = createField("node_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 状态，参考td_job_status
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Short> STATUS = createField("status", org.jooq.impl.SQLDataType.SMALLINT, this);

	/**
	 * 计划执行时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> PLANTIME = createField("plantime", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 开始时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> STARTTIME = createField("starttime", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 结束时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> ENDTIME = createField("endtime", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 输出提示信息
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> OUTPUT_MSG = createField("output_msg", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 备注
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> MEMO = createField("memo", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.twf_log_subjob.is_test</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> IS_TEST = createField("is_test", org.jooq.impl.SQLDataType.TINYINT, this);

	public TwfLogSubjob() {
		super("twf_log_subjob", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfLogSubjob(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfLogSubjob.TWF_LOG_SUBJOB);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TWF_LOG_SUBJOB;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TWF_LOG_SUBJOB_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TWF_LOG_SUBJOB_PRIMARY, com.yunat.ccms.jooq.Keys.KEY_TWF_LOG_SUBJOB_UK_TWF_LOG_SUBJOB_JOB_ID_NODE_ID);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfLogSubjob as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfLogSubjob(alias);
	}
}
