/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 活动执行用户组列表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfLogGroup extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -557070708;

	/**
	 * The singleton instance of ccms.twf_log_group
	 */
	public static final com.yunat.ccms.jooq.tables.TwfLogGroup TWF_LOG_GROUP = new com.yunat.ccms.jooq.tables.TwfLogGroup();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.twf_log_group.subjob_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> SUBJOB_ID = createField("subjob_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.twf_log_group.node_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> NODE_ID = createField("node_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 用户组类型，见td_group_type
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Short> GROUP_TYPE = createField("group_type", org.jooq.impl.SQLDataType.SMALLINT, this);

	/**
	 * 创建时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATETIME = createField("createtime", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The table column <code>ccms.twf_log_group.job_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> JOB_ID = createField("job_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.twf_log_group.user_count_sending</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> USER_COUNT_SENDING = createField("user_count_sending", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>ccms.twf_log_group.user_count_control</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> USER_COUNT_CONTROL = createField("user_count_control", org.jooq.impl.SQLDataType.INTEGER, this);

	public TwfLogGroup() {
		super("twf_log_group", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfLogGroup(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfLogGroup.TWF_LOG_GROUP);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfLogGroup as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfLogGroup(alias);
	}
}
