/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 流程节点间数据传输记录保存
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfLogJobData extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1271198293;

	/**
	 * The singleton instance of ccms.twf_log_job_data
	 */
	public static final com.yunat.ccms.jooq.tables.TwfLogJobData TWF_LOG_JOB_DATA = new com.yunat.ccms.jooq.tables.TwfLogJobData();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.twf_log_job_data.subjob_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> SUBJOB_ID = createField("subjob_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.twf_log_job_data.job_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> JOB_ID = createField("job_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.twf_log_job_data.camp_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> CAMP_ID = createField("camp_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 源节点id
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> SOURCE = createField("source", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 目标节点id
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> TARGET = createField("target", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 数据类型
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DATA_TYPE = createField("data_type", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 数据名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DATA_CODE = createField("data_code", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TwfLogJobData() {
		super("twf_log_job_data", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfLogJobData(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfLogJobData.TWF_LOG_JOB_DATA);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfLogJobData as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfLogJobData(alias);
	}
}
