/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 流程执行中间表列表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfLogNodeMids extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 2035969686;

	/**
	 * The singleton instance of ccms.twf_log_node_mids
	 */
	public static final com.yunat.ccms.jooq.tables.TwfLogNodeMids TWF_LOG_NODE_MIDS = new com.yunat.ccms.jooq.tables.TwfLogNodeMids();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.twf_log_node_mids.job_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> JOB_ID = createField("job_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 表或视图名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TABLE_VIEW_NAME = createField("table_view_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 表或视图类型
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TABLE_VIEW_TYPE = createField("table_view_type", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.twf_log_node_mids.created_time</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED_TIME = createField("created_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	public TwfLogNodeMids() {
		super("twf_log_node_mids", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfLogNodeMids(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfLogNodeMids.TWF_LOG_NODE_MIDS);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfLogNodeMids as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfLogNodeMids(alias);
	}
}
