/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 渠道执行日志表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfLogChannel extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -370723494;

	/**
	 * The singleton instance of ccms.twf_log_channel
	 */
	public static final com.yunat.ccms.jooq.tables.TwfLogChannel TWF_LOG_CHANNEL = new com.yunat.ccms.jooq.tables.TwfLogChannel();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.twf_log_channel.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 节点任务ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> SUBJOB_ID = createField("subjob_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 渠道ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> CHANNEL_ID = createField("channel_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * 创建时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 计划开始时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> PLAN_START_TIME = createField("plan_start_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 计划结束时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> PLAN_END_TIME = createField("plan_end_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 活动ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> CAMPAIGN_ID = createField("campaign_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 节点ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> NODE_ID = createField("node_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 渠道类型，比如SMS MMS
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> CHANNEL_TYPE = createField("channel_type", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>ccms.twf_log_channel.is_test_execute</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> IS_TEST_EXECUTE = createField("is_test_execute", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The table column <code>ccms.twf_log_channel.task_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TASK_ID = createField("task_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TwfLogChannel() {
		super("twf_log_channel", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfLogChannel(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfLogChannel.TWF_LOG_CHANNEL);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TWF_LOG_CHANNEL;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TWF_LOG_CHANNEL_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TWF_LOG_CHANNEL_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfLogChannel as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfLogChannel(alias);
	}
}
