/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 优惠券节点配置
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfNodeCoupon extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -1545635068;

	/**
	 * The singleton instance of ccms.twf_node_coupon
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeCoupon TWF_NODE_COUPON = new com.yunat.ccms.jooq.tables.TwfNodeCoupon();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 节点ID
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> NODE_ID = createField("node_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 发送渠道ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> CHANNEL_ID = createField("channel_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 店铺ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SHOP_ID = createField("shop_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 优惠券ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> COUPON_ID = createField("coupon_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 测试用户
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PREVIEW_CUSTOMERS = createField("preview_customers", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * 输出控制；1：发送组中发送成功客户和控制组客户 2：全量客户
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> OUTPUT_CONTROL = createField("output_control", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 备注
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TwfNodeCoupon() {
		super("twf_node_coupon", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfNodeCoupon(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfNodeCoupon.TWF_NODE_COUPON);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_COUPON_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_COUPON_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfNodeCoupon as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfNodeCoupon(alias);
	}
}
