/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfNodeEvaluateOrderDetail extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 217524686;

	/**
	 * The singleton instance of ccms.twf_node_evaluate_order_detail
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeEvaluateOrderDetail TWF_NODE_EVALUATE_ORDER_DETAIL = new com.yunat.ccms.jooq.tables.TwfNodeEvaluateOrderDetail();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 评估报表订单(明细)主键
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> EVALUATE_ORDER_ID = createField("evaluate_order_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.twf_node_evaluate_order_detail.job_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> JOB_ID = createField("job_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.twf_node_evaluate_order_detail.node_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> NODE_ID = createField("node_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.twf_node_evaluate_order_detail.evaluate_time</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Date> EVALUATE_TIME = createField("evaluate_time", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * The table column <code>ccms.twf_node_evaluate_order_detail.tid</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TID = createField("tid", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.twf_node_evaluate_order_detail.customerno</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CUSTOMERNO = createField("customerno", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.twf_node_evaluate_order_detail.created</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The table column <code>ccms.twf_node_evaluate_order_detail.pay_time</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> PAY_TIME = createField("pay_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The table column <code>ccms.twf_node_evaluate_order_detail.consign_time</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CONSIGN_TIME = createField("consign_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The table column <code>ccms.twf_node_evaluate_order_detail.total_fee</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> TOTAL_FEE = createField("total_fee", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * The table column <code>ccms.twf_node_evaluate_order_detail.payment</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> PAYMENT = createField("payment", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * The table column <code>ccms.twf_node_evaluate_order_detail.status</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TwfNodeEvaluateOrderDetail() {
		super("twf_node_evaluate_order_detail", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfNodeEvaluateOrderDetail(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfNodeEvaluateOrderDetail.TWF_NODE_EVALUATE_ORDER_DETAIL);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TWF_NODE_EVALUATE_ORDER_DETAIL;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_EVALUATE_ORDER_DETAIL_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_EVALUATE_ORDER_DETAIL_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfNodeEvaluateOrderDetail as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfNodeEvaluateOrderDetail(alias);
	}
}
