/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 短信节点
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfNodeSms extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 200296421;

	/**
	 * The singleton instance of ccms.twf_node_sms
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeSms TWF_NODE_SMS = new com.yunat.ccms.jooq.tables.TwfNodeSms();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 节点ID
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> NODE_ID = createField("node_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 可否订阅 0-否 1-可
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> UNSUBSCRIBE_ENABLED = createField("unsubscribe_enabled", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * 屏蔽黑名单 0-否 1-是
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> BLACKLIST_DISABLED = createField("blacklist_disabled", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * 发送红名单 0-不 1-是
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> REDLIST_ENABLED = createField("redlist_enabled", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * 发送通道ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> DELIVERY_CHANNEL_ID = createField("delivery_channel_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * 测试执行号码串
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TEST_PHONE_STRING = createField("test_phone_string", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 发送类别
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DELIVERY_CATEGORY = createField("delivery_category", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 短信内容
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> MESSAGE_VALUE = createField("message_value", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * 手机号码来源
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PHONE_NUM_SOURCE = createField("phone_num_source", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 输出控制
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> OUTPUT_CONTROL = createField("output_control", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 发送方式选择
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DELIVERY_SELECTION = createField("delivery_selection", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 指定发送日期，字符各式 YYYY-MM-DD
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> ASSIGN_DELIVERY_DATE = createField("assign_delivery_date", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 指定发送时分，字符各式 HH:MM
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> ASSIGN_DELIVERY_TIME = createField("assign_delivery_time", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 是否超时预设时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> OVER_ASSIGN_DELIVERY_PERIOD = createField("over_assign_delivery_period", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * 可抽样 0-不可 1-可
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> SAMPLING_ENABLED = createField("sampling_enabled", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * 抽样数
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> SAMPLING_COPIES = createField("sampling_copies", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * 备注
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 创建时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	public TwfNodeSms() {
		super("twf_node_sms", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfNodeSms(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfNodeSms.TWF_NODE_SMS);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_SMS_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_SMS_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfNodeSms as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfNodeSms(alias);
	}
}
