/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfNodeEvaluate extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1651754398;

	/**
	 * The singleton instance of ccms.twf_node_evaluate
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeEvaluate TWF_NODE_EVALUATE = new com.yunat.ccms.jooq.tables.TwfNodeEvaluate();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 评估节点ID
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> NODE_ID = createField("node_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 评估节点名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> NODE_NAME = createField("node_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 评估周期（1天~7天）
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> EVALUATE_CYCLE = createField("evaluate_cycle", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * 评估的店铺
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SHOP_ID = createField("shop_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.twf_node_evaluate.created</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	public TwfNodeEvaluate() {
		super("twf_node_evaluate", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfNodeEvaluate(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfNodeEvaluate.TWF_NODE_EVALUATE);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_EVALUATE_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_EVALUATE_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfNodeEvaluate as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfNodeEvaluate(alias);
	}
}
