/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfNodeTypeMid2Toolbar extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1804889955;

	/**
	 * The singleton instance of ccms.twf_node_type_mid2_toolbar
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeTypeMid2Toolbar TWF_NODE_TYPE_MID2_TOOLBAR = new com.yunat.ccms.jooq.tables.TwfNodeTypeMid2Toolbar();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 主键ID
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 对应twf_node_type
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> NODE_CONFIG_ID = createField("node_config_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 对应表twf_mid_toolbar_node_type
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> MID_ID = createField("mid_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 是否disabled, true该节点显示但是不可以拖动节点到画布
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> DISABLED = createField("disabled", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * 备注
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TwfNodeTypeMid2Toolbar() {
		super("twf_node_type_mid2_toolbar", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfNodeTypeMid2Toolbar(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfNodeTypeMid2Toolbar.TWF_NODE_TYPE_MID2_TOOLBAR);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TWF_NODE_TYPE_MID2_TOOLBAR;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_TYPE_MID2_TOOLBAR_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_TYPE_MID2_TOOLBAR_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfNodeTypeMid2Toolbar as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfNodeTypeMid2Toolbar(alias);
	}
}
