/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 时间节点的配置信息
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfNodeTime extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -1807503636;

	/**
	 * The singleton instance of ccms.twf_node_time
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeTime TWF_NODE_TIME = new com.yunat.ccms.jooq.tables.TwfNodeTime();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.twf_node_time.node_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> NODE_ID = createField("node_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.twf_node_time.iscycle</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> ISCYCLE = createField("iscycle", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The table column <code>ccms.twf_node_time.isrealtime</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> ISREALTIME = createField("isrealtime", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * 非周期性的开始日期
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Date> REALTIME_BEGIN_DATE = createField("realtime_begin_date", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * 非周期性的开始时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> REALTIME_BEGIN_TIME = createField("realtime_begin_time", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 周期性的开始日期
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Date> CYCLE_BEGIN_DATE = createField("cycle_begin_date", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * 周期性的结束日期
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Date> CYCLE_END_DATE = createField("cycle_end_date", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * 周期性的开始时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CYCLE_BEGIN_TIME = createField("cycle_begin_time", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 周期类型： day 每天 week 每周 month 每月
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CYCLE_TYPE = createField("cycle_type", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 周期值
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CYCLE_VALUE = createField("cycle_value", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TwfNodeTime() {
		super("twf_node_time", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfNodeTime(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfNodeTime.TWF_NODE_TIME);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_TIME_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_TIME_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfNodeTime as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfNodeTime(alias);
	}
}
