/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 节点重试表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfNodeRetry extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -727999175;

	/**
	 * The singleton instance of ccms.twf_node_retry
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeRetry TWF_NODE_RETRY = new com.yunat.ccms.jooq.tables.TwfNodeRetry();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.twf_node_retry.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.twf_node_retry.job_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> JOB_ID = createField("job_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.twf_node_retry.node_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> NODE_ID = createField("node_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.twf_node_retry.is_test_execute</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> IS_TEST_EXECUTE = createField("is_test_execute", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The table column <code>ccms.twf_node_retry.failed_reason</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> FAILED_REASON = createField("failed_reason", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.twf_node_retry.failed_code</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> FAILED_CODE = createField("failed_code", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TwfNodeRetry() {
		super("twf_node_retry", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfNodeRetry(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfNodeRetry.TWF_NODE_RETRY);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TWF_NODE_RETRY;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_RETRY_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_RETRY_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfNodeRetry as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfNodeRetry(alias);
	}
}
