/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 已定义的查询条件（来自于用户界面）
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfNodeQueryCriteria extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1203913082;

	/**
	 * The singleton instance of ccms.twf_node_query_criteria
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeQueryCriteria TWF_NODE_QUERY_CRITERIA = new com.yunat.ccms.jooq.tables.TwfNodeQueryCriteria();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.twf_node_query_criteria.node_criteria_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> NODE_CRITERIA_ID = createField("node_criteria_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 条件模版ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> QUERY_CRITERIA_ID = createField("query_criteria_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 已定义查询ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> QUERY_DEFINED_ID = createField("query_defined_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 操作符
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> OPERATOR = createField("operator", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 目标值
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TARGET_VALUE = createField("target_value", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 嵌套的标识, 仅支持嵌套一层, 空表示字段不嵌套
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SUB_GROUP = createField("sub_group", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 关系符and or, 空默认为and
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> RELATION = createField("relation", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * UI标识
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> UI_CODE = createField("ui_code", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TwfNodeQueryCriteria() {
		super("twf_node_query_criteria", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfNodeQueryCriteria(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfNodeQueryCriteria.TWF_NODE_QUERY_CRITERIA);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TWF_NODE_QUERY_CRITERIA;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_QUERY_CRITERIA_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_QUERY_CRITERIA_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfNodeQueryCriteria as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfNodeQueryCriteria(alias);
	}
}
