/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfNodeEvaluateCustomerDetail extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -587372139;

	/**
	 * The singleton instance of ccms.twf_node_evaluate_customer_detail
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeEvaluateCustomerDetail TWF_NODE_EVALUATE_CUSTOMER_DETAIL = new com.yunat.ccms.jooq.tables.TwfNodeEvaluateCustomerDetail();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 评估报表客户明细主键
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> EVALUATE_CUSTOMER_ID = createField("evaluate_customer_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 执行ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> JOB_ID = createField("job_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 节点ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> NODE_ID = createField("node_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 评估时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Date> EVALUATE_TIME = createField("evaluate_time", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * 平台唯一标识
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> UNI_ID = createField("uni_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> FULL_NAME = createField("full_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 性别
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SEX = createField("sex", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 生日
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Date> BIRTHDAY = createField("birthday", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * 省份
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 城市
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 区县
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DISTRICT = createField("district", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * vip信息
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> VIP_INFO = createField("vip_info", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 电话
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> MOBILE = createField("mobile", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * email
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 买家信用等级
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> BUYER_CREDIT_LEV = createField("buyer_credit_lev", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 买家好评率
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> GOOD_RATE = createField("good_rate", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 地址
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 邮编
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> ZIP = createField("zip", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 职业
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> JOB = createField("job", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TwfNodeEvaluateCustomerDetail() {
		super("twf_node_evaluate_customer_detail", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfNodeEvaluateCustomerDetail(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfNodeEvaluateCustomerDetail.TWF_NODE_EVALUATE_CUSTOMER_DETAIL);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TWF_NODE_EVALUATE_CUSTOMER_DETAIL;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_EVALUATE_CUSTOMER_DETAIL_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_EVALUATE_CUSTOMER_DETAIL_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfNodeEvaluateCustomerDetail as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfNodeEvaluateCustomerDetail(alias);
	}
}
