/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 查询节点
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfNodeQuery extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -639180148;

	/**
	 * The singleton instance of ccms.twf_node_query
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeQuery TWF_NODE_QUERY = new com.yunat.ccms.jooq.tables.TwfNodeQuery();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 需要指定，不自增
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> NODE_ID = createField("node_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 是否排除
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> IS_EXCLUDE = createField("is_exclude", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * 时间类型
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> TIME_TYPE = createField("time_type", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * 平台
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PLAT_CODE = createField("plat_code", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TwfNodeQuery() {
		super("twf_node_query", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfNodeQuery(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfNodeQuery.TWF_NODE_QUERY);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_QUERY_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_QUERY_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfNodeQuery as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfNodeQuery(alias);
	}
}
