/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 短信节点执行后生成数据
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfNodeSmsExecutionRecord extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 441120370;

	/**
	 * The singleton instance of ccms.twf_node_sms_execution_record
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeSmsExecutionRecord TWF_NODE_SMS_EXECUTION_RECORD = new com.yunat.ccms.jooq.tables.TwfNodeSmsExecutionRecord();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.twf_node_sms_execution_record.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 节点ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> NODE_ID = createField("node_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.twf_node_sms_execution_record.subjob_id</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> SUBJOB_ID = createField("subjob_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 目标组用户数
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> TARGET_GROUP_CUSTOMERS = createField("target_group_customers", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 控制组用户数
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> CONTROL_GROUP_CUSTOMERS = createField("control_group_customers", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 有效手机号码数
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> VALID_PHONE_AMOUNT = createField("valid_phone_amount", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 无效手机号码数
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> INVALID_PHONE_AMOUNT = createField("invalid_phone_amount", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 短信发送条数
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> SENDING_TOTAL_NUM = createField("sending_total_num", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 发送单价
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> SENDING_PRICE = createField("sending_price", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * 创建时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED_TIME = createField("created_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	public TwfNodeSmsExecutionRecord() {
		super("twf_node_sms_execution_record", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfNodeSmsExecutionRecord(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfNodeSmsExecutionRecord.TWF_NODE_SMS_EXECUTION_RECORD);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TWF_NODE_SMS_EXECUTION_RECORD;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_SMS_EXECUTION_RECORD_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_SMS_EXECUTION_RECORD_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfNodeSmsExecutionRecord as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfNodeSmsExecutionRecord(alias);
	}
}
