/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 保存流程的节点信息
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfNode extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 99602522;

	/**
	 * The singleton instance of ccms.twf_node
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNode TWF_NODE = new com.yunat.ccms.jooq.tables.TwfNode();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The table column <code>ccms.twf_node.node_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> NODE_ID = createField("node_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 名字
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.twf_node.style</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> STYLE = createField("style", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.twf_node.vertex</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> VERTEX = createField("vertex", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 流程id
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> WORKFLOW_ID = createField("workflow_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>ccms.twf_node.x</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> X = createField("x", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>ccms.twf_node.y</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> Y = createField("y", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>ccms.twf_node.width</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> WIDTH = createField("width", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>ccms.twf_node.height</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> HEIGHT = createField("height", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>ccms.twf_node.as_t</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> AS_T = createField("as_t", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 节点类型
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 节点描述信息（不超过140个汉字）
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TwfNode() {
		super("twf_node", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfNode(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfNode.TWF_NODE);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TWF_NODE;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfNode as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfNode(alias);
	}
}
