/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 评估节点_商品明细
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfNodeEvaluateProductDetail extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -1808850160;

	/**
	 * The singleton instance of ccms.twf_node_evaluate_product_detail
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeEvaluateProductDetail TWF_NODE_EVALUATE_PRODUCT_DETAIL = new com.yunat.ccms.jooq.tables.TwfNodeEvaluateProductDetail();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 评估报表商品明细主键
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> EVALUATE_PRODUCT_ID = createField("evaluate_product_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 执行jobId
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> JOB_ID = createField("job_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 节点ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> NODE_ID = createField("node_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 评估时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Date> EVALUATE_TIME = createField("evaluate_time", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * 商品ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PRODUCT_ID = createField("product_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 商品名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PRODUCT_NAME = createField("product_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 购买客户数
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> CUSTOMER_COUNT = createField("customer_count", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * 订单数
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> ORDER_COUNT = createField("order_count", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * 购买数量
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> BUY_NUM = createField("buy_num", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * 购买金额
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> BUY_FEE = createField("buy_fee", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * 商家编码
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> OUTER_ID = createField("outer_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TwfNodeEvaluateProductDetail() {
		super("twf_node_evaluate_product_detail", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfNodeEvaluateProductDetail(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfNodeEvaluateProductDetail.TWF_NODE_EVALUATE_PRODUCT_DETAIL);
	}

	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Long> getIdentity() {
		return com.yunat.ccms.jooq.Keys.IDENTITY_TWF_NODE_EVALUATE_PRODUCT_DETAIL;
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_EVALUATE_PRODUCT_DETAIL_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_EVALUATE_PRODUCT_DETAIL_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfNodeEvaluateProductDetail as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfNodeEvaluateProductDetail(alias);
	}
}
