/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 目标组节点
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TwfNodeTarget extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 494217942;

	/**
	 * The singleton instance of ccms.twf_node_target
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeTarget TWF_NODE_TARGET = new com.yunat.ccms.jooq.tables.TwfNodeTarget();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 节点ID
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Long> NODE_ID = createField("node_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * 名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 控制组生成方式： 1 百分比 2 人数 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> CONTROL_GROUP_TYPE = createField("control_group_type", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * 控制组生成值，或者是百分比，或者是指定的人数
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CONTROL_GROUP_VALUE = createField("control_group_value", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 备注
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 创建时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	public TwfNodeTarget() {
		super("twf_node_target", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public TwfNodeTarget(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.TwfNodeTarget.TWF_NODE_TARGET);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_TARGET_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_TWF_NODE_TARGET_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.TwfNodeTarget as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.TwfNodeTarget(alias);
	}
}
