/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 客户统一信息表
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class UniCustomer extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 876888469;

	/**
	 * The singleton instance of ccms.uni_customer
	 */
	public static final com.yunat.ccms.jooq.tables.UniCustomer UNI_CUSTOMER = new com.yunat.ccms.jooq.tables.UniCustomer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 主键。客户全局统一ID，由客户统一ID生成规则生成
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> UNI_ID = createField("uni_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 姓名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> FULL_NAME = createField("full_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 性别，m : 男； f : 女
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SEX = createField("sex", org.jooq.impl.SQLDataType.CHAR, this);

	/**
	 * 职业
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> JOB = createField("job", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 出生年份，四位整数
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Short> BIRTH_YEAR = createField("birth_year", org.jooq.impl.SQLDataType.SMALLINT, this);

	/**
	 * 生日
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Date> BIRTHDAY = createField("birthday", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * 手机号
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> MOBILE = createField("mobile", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 电子邮件地址
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 座机号码
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 邮编
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> ZIP = createField("zip", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 国家
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> COUNTRY = createField("country", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 省份
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 城市（地级）
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 区县（县级）
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DISTRICT = createField("district", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 地址
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR, this);

	public UniCustomer() {
		super("uni_customer", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public UniCustomer(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.UniCustomer.UNI_CUSTOMER);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_UNI_CUSTOMER_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_UNI_CUSTOMER_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.UniCustomer as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.UniCustomer(alias);
	}
}
