/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * 客户来源平台信息
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class UniPlat extends org.jooq.impl.UpdatableTableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -224409156;

	/**
	 * The singleton instance of ccms.uni_plat
	 */
	public static final com.yunat.ccms.jooq.tables.UniPlat UNI_PLAT = new com.yunat.ccms.jooq.tables.UniPlat();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 来源平台代码, 固定8位以内的字符， 如：taobao，jingdong 等
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PLAT_CODE = createField("plat_code", org.jooq.impl.SQLDataType.CHAR, this);

	/**
	 * 当前平台客户的父平台代码。如：“我的中心”平台的父平台是淘宝平台
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PARENT_PLAT = createField("parent_plat", org.jooq.impl.SQLDataType.CHAR, this);

	/**
	 * 客户来源平台的数据库表名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PLAT_TABLE = createField("plat_table", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 客户所属来源平台的优先级。平台优先级是从0开始的自然数，0最高，数字越大优先级越低
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Short> PLAT_PRIORITY = createField("plat_priority", org.jooq.impl.SQLDataType.SMALLINT, this);

	/**
	 * 是否将当前平台存在而父平台不存在的客户同步插入到父平台的客户表中？
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> SYNC_PARENT = createField("sync_parent", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * 平台中的客户记录是否被允许删除？默认为不允许。当允许删除时，其对应的统一客户表和客户关系表的记录也通过触发器一并被删除
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> ENABLE_DELETE = createField("enable_delete", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * 客户来源平台的描述
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PLAT_DESC = createField("plat_desc", org.jooq.impl.SQLDataType.VARCHAR, this);

	public UniPlat() {
		super("uni_plat", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public UniPlat(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.UniPlat.UNI_PLAT);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getMainKey() {
		return com.yunat.ccms.jooq.Keys.KEY_UNI_PLAT_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(com.yunat.ccms.jooq.Keys.KEY_UNI_PLAT_PRIMARY);
	}

	@Override
	public com.yunat.ccms.jooq.tables.UniPlat as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.UniPlat(alias);
	}
}
