/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * VIEW
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class VmTaobaoOrder extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -1879296747;

	/**
	 * The singleton instance of ccms.vm_taobao_order
	 */
	public static final com.yunat.ccms.jooq.tables.VmTaobaoOrder VM_TAOBAO_ORDER = new com.yunat.ccms.jooq.tables.VmTaobaoOrder();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 订单号
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TID = createField("tid", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 客户ID
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CUSTOMERNO = createField("customerno", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 收货人的姓名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> RECEIVER_NAME = createField("receiver_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 交易创建时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 付款时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> PAY_TIME = createField("pay_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 卖家发货时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CONSIGN_TIME = createField("consign_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * 店铺名称，即店主用户昵称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SHOP_NAME = createField("shop_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 实付金额。精确到2位小数;单位:元。如:200.07，表示:200元7分
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> PAYMENT = createField("payment", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * 邮费
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> POST_FEE = createField("post_fee", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * 收货人的手机号码
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> RECEIVER_MOBILE = createField("receiver_mobile", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 买家支付宝账号
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> BUYER_ALIPAY_NO = createField("buyer_alipay_no", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 买家邮件地址
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> BUYER_EMAIL = createField("buyer_email", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 商品金额
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> TOTAL_FEE = createField("total_fee", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * The table column <code>ccms.vm_taobao_order.status</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 用户手机号
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> BUYER_MOBILE = createField("buyer_mobile", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 运单号.具体一个物流公司的运单号码.
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> OUT_SID = createField("out_sid", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 物流公司名称
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> COMPANY_NAME = createField("company_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 运单创建时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> SHIPPING_CREATED = createField("shipping_created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	public VmTaobaoOrder() {
		super("vm_taobao_order", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public VmTaobaoOrder(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.VmTaobaoOrder.VM_TAOBAO_ORDER);
	}

	@Override
	public com.yunat.ccms.jooq.tables.VmTaobaoOrder as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.VmTaobaoOrder(alias);
	}
}
