/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * VIEW
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class VwTaobaoCustomer extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1338702170;

	/**
	 * The singleton instance of ccms.vw_taobao_customer
	 */
	public static final com.yunat.ccms.jooq.tables.VwTaobaoCustomer VW_TAOBAO_CUSTOMER = new com.yunat.ccms.jooq.tables.VwTaobaoCustomer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * 主键。客户全局统一ID，由客户统一ID生成规则生成
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> UNI_ID = createField("uni_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 用户id，CCMS系统用户ID,淘宝UID(number)
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CUSTOMERNO = createField("customerno", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 姓名
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> FULL_NAME = createField("full_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 性别，m : 男； f : 女
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> SEX = createField("sex", org.jooq.impl.SQLDataType.CHAR, this);

	/**
	 * 职业
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> JOB = createField("job", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.vw_taobao_customer.age</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> AGE = createField("age", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * 生日
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Date> BIRTHDAY = createField("birthday", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * 电子邮件地址
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 手机号
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> MOBILE = createField("mobile", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 省份
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 城市（地级）
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 区县（县级）
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DISTRICT = createField("district", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 地址
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 邮编
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> ZIP = createField("zip", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.vw_taobao_customer.is_mobile_valid</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> IS_MOBILE_VALID = createField("is_mobile_valid", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.vw_taobao_customer.is_email_valid</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> IS_EMAIL_VALID = createField("is_email_valid", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 用户的全站vip信息，可取值如下：c(普通会员),asso_vip(荣誉会员)，vip1,vip2,vip3,vip4,vip5,vip6(六个等级的正式vip会员)，共8种取值，其中asso_vip是由vip会员衰退而成，与主站上的vip0对应。
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> VIP_INFO = createField("vip_info", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 买家信用等级
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> BUYER_CREDIT_LEV = createField("buyer_credit_lev", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * 用户淘宝注册时间
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The table column <code>ccms.vw_taobao_customer.buyer_good_ratio</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.math.BigDecimal> BUYER_GOOD_RATIO = createField("buyer_good_ratio", org.jooq.impl.SQLDataType.DECIMAL, this);

	/**
	 * The table column <code>ccms.vw_taobao_customer.ymd</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> YMD = createField("ymd", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.vw_taobao_customer.ym</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> YM = createField("ym", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * 会员等级，1：普通会员，2：高级会员，3：vip会员，4：至尊vip
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> GRADE = createField("grade", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>ccms.vw_taobao_customer.AS　label_name</code>
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> AS_LABEL_NAME = createField("AS　label_name", org.jooq.impl.SQLDataType.VARCHAR, this);

	public VwTaobaoCustomer() {
		super("vw_taobao_customer", com.yunat.ccms.jooq.Ccms.CCMS);
	}

	public VwTaobaoCustomer(java.lang.String alias) {
		super(alias, com.yunat.ccms.jooq.Ccms.CCMS, com.yunat.ccms.jooq.tables.VwTaobaoCustomer.VW_TAOBAO_CUSTOMER);
	}

	@Override
	public com.yunat.ccms.jooq.tables.VwTaobaoCustomer as(java.lang.String alias) {
		return new com.yunat.ccms.jooq.tables.VwTaobaoCustomer(alias);
	}
}
