/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class Ccms extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 2817806;

	/**
	 * The singleton instance of ccms
	 */
	public static final Ccms CCMS = new Ccms();

	/**
	 * No further instances allowed
	 */
	private Ccms() {
		super("ccms");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List<org.jooq.Table<?>> result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.yunat.ccms.jooq.tables.PltExtaobaoCustomer.PLT_EXTAOBAO_CUSTOMER,
			com.yunat.ccms.jooq.tables.PltExtBatchCustomer.PLT_EXT_BATCH_CUSTOMER,
			com.yunat.ccms.jooq.tables.PltExtCustomer.PLT_EXT_CUSTOMER,
			com.yunat.ccms.jooq.tables.PltExtImportBatch.PLT_EXT_IMPORT_BATCH,
			com.yunat.ccms.jooq.tables.PltKfgztCustomer.PLT_KFGZT_CUSTOMER,
			com.yunat.ccms.jooq.tables.PltKfgztCustomerLabel.PLT_KFGZT_CUSTOMER_LABEL,
			com.yunat.ccms.jooq.tables.PltKfgztShopLabel.PLT_KFGZT_SHOP_LABEL,
			com.yunat.ccms.jooq.tables.PltModifyCustomer.PLT_MODIFY_CUSTOMER,
			com.yunat.ccms.jooq.tables.PltModifyCustomerLog.PLT_MODIFY_CUSTOMER_LOG,
			com.yunat.ccms.jooq.tables.PltTaobaoCoupon.PLT_TAOBAO_COUPON,
			com.yunat.ccms.jooq.tables.PltTaobaoCouponDenomination.PLT_TAOBAO_COUPON_DENOMINATION,
			com.yunat.ccms.jooq.tables.PltTaobaoCrmMember.PLT_TAOBAO_CRM_MEMBER,
			com.yunat.ccms.jooq.tables.PltTaobaoCustomer.PLT_TAOBAO_CUSTOMER,
			com.yunat.ccms.jooq.tables.PltTaobaoItemCat.PLT_TAOBAO_ITEM_CAT,
			com.yunat.ccms.jooq.tables.PltTaobaoItemProp.PLT_TAOBAO_ITEM_PROP,
			com.yunat.ccms.jooq.tables.PltTaobaoItemPropVal.PLT_TAOBAO_ITEM_PROP_VAL,
			com.yunat.ccms.jooq.tables.PltTaobaoItemSellerCat.PLT_TAOBAO_ITEM_SELLER_CAT,
			com.yunat.ccms.jooq.tables.PltTaobaoOrder.PLT_TAOBAO_ORDER,
			com.yunat.ccms.jooq.tables.PltTaobaoOrderItem.PLT_TAOBAO_ORDER_ITEM,
			com.yunat.ccms.jooq.tables.PltTaobaoOrderType.PLT_TAOBAO_ORDER_TYPE,
			com.yunat.ccms.jooq.tables.PltTaobaoPayType.PLT_TAOBAO_PAY_TYPE,
			com.yunat.ccms.jooq.tables.PltTaobaoProduct.PLT_TAOBAO_PRODUCT,
			com.yunat.ccms.jooq.tables.PltTaobaoProductProp.PLT_TAOBAO_PRODUCT_PROP,
			com.yunat.ccms.jooq.tables.PltTaobaoProductSellerCat.PLT_TAOBAO_PRODUCT_SELLER_CAT,
			com.yunat.ccms.jooq.tables.PltTaobaoShipping.PLT_TAOBAO_SHIPPING,
			com.yunat.ccms.jooq.tables.PltTaobaoShop.PLT_TAOBAO_SHOP,
			com.yunat.ccms.jooq.tables.PltTaobaoTargetType.PLT_TAOBAO_TARGET_TYPE,
			com.yunat.ccms.jooq.tables.PltTaobaoTraderate.PLT_TAOBAO_TRADERATE,
			com.yunat.ccms.jooq.tables.PltWdzxCustomer.PLT_WDZX_CUSTOMER,
			com.yunat.ccms.jooq.tables.PltWdzxEmailSubscribe.PLT_WDZX_EMAIL_SUBSCRIBE,
			com.yunat.ccms.jooq.tables.TbAppExpired.TB_APP_EXPIRED,
			com.yunat.ccms.jooq.tables.TbAppProperties.TB_APP_PROPERTIES,
			com.yunat.ccms.jooq.tables.TbCampaign.TB_CAMPAIGN,
			com.yunat.ccms.jooq.tables.TbCampInvestigateComments.TB_CAMP_INVESTIGATE_COMMENTS,
			com.yunat.ccms.jooq.tables.TbChannel.TB_CHANNEL,
			com.yunat.ccms.jooq.tables.TbFunctionLimit.TB_FUNCTION_LIMIT,
			com.yunat.ccms.jooq.tables.TbProgram.TB_PROGRAM,
			com.yunat.ccms.jooq.tables.TbRemoteLogException.TB_REMOTE_LOG_EXCEPTION,
			com.yunat.ccms.jooq.tables.TbRole.TB_ROLE,
			com.yunat.ccms.jooq.tables.TbRolePermission.TB_ROLE_PERMISSION,
			com.yunat.ccms.jooq.tables.TbSysuser.TB_SYSUSER,
			com.yunat.ccms.jooq.tables.TbSysTaobaoUser.TB_SYS_TAOBAO_USER,
			com.yunat.ccms.jooq.tables.TbTemplate.TB_TEMPLATE,
			com.yunat.ccms.jooq.tables.TbUserRole.TB_USER_ROLE,
			com.yunat.ccms.jooq.tables.TdsCampaignStatus.TDS_CAMPAIGN_STATUS,
			com.yunat.ccms.jooq.tables.TdsJobStatus.TDS_JOB_STATUS,
			com.yunat.ccms.jooq.tables.TdsOrderStatus.TDS_ORDER_STATUS,
			com.yunat.ccms.jooq.tables.TdsPermission.TDS_PERMISSION,
			com.yunat.ccms.jooq.tables.TdsSubjobStatus.TDS_SUBJOB_STATUS,
			com.yunat.ccms.jooq.tables.TduCampaignCategory.TDU_CAMPAIGN_CATEGORY,
			com.yunat.ccms.jooq.tables.TduProgType.TDU_PROG_TYPE,
			com.yunat.ccms.jooq.tables.TmCatalog.TM_CATALOG,
			com.yunat.ccms.jooq.tables.TmCatalogCriteria.TM_CATALOG_CRITERIA,
			com.yunat.ccms.jooq.tables.TmDbColumn.TM_DB_COLUMN,
			com.yunat.ccms.jooq.tables.TmDbTable.TM_DB_TABLE,
			com.yunat.ccms.jooq.tables.TmDic.TM_DIC,
			com.yunat.ccms.jooq.tables.TmDicValue.TM_DIC_VALUE,
			com.yunat.ccms.jooq.tables.TmQuery.TM_QUERY,
			com.yunat.ccms.jooq.tables.TmQueryColumn.TM_QUERY_COLUMN,
			com.yunat.ccms.jooq.tables.TmQueryCriteria.TM_QUERY_CRITERIA,
			com.yunat.ccms.jooq.tables.TmQueryJoinCriteria.TM_QUERY_JOIN_CRITERIA,
			com.yunat.ccms.jooq.tables.TmQueryTable.TM_QUERY_TABLE,
			com.yunat.ccms.jooq.tables.TmRefer.TM_REFER,
			com.yunat.ccms.jooq.tables.TwfConnect.TWF_CONNECT,
			com.yunat.ccms.jooq.tables.TwfLogChannel.TWF_LOG_CHANNEL,
			com.yunat.ccms.jooq.tables.TwfLogChannelUser.TWF_LOG_CHANNEL_USER,
			com.yunat.ccms.jooq.tables.TwfLogGroup.TWF_LOG_GROUP,
			com.yunat.ccms.jooq.tables.TwfLogGroupUser.TWF_LOG_GROUP_USER,
			com.yunat.ccms.jooq.tables.TwfLogJob.TWF_LOG_JOB,
			com.yunat.ccms.jooq.tables.TwfLogJobData.TWF_LOG_JOB_DATA,
			com.yunat.ccms.jooq.tables.TwfLogNodeMids.TWF_LOG_NODE_MIDS,
			com.yunat.ccms.jooq.tables.TwfLogSubjob.TWF_LOG_SUBJOB,
			com.yunat.ccms.jooq.tables.TwfNode.TWF_NODE,
			com.yunat.ccms.jooq.tables.TwfNodeCoupon.TWF_NODE_COUPON,
			com.yunat.ccms.jooq.tables.TwfNodeEvaluate.TWF_NODE_EVALUATE,
			com.yunat.ccms.jooq.tables.TwfNodeEvaluateCustomerDetail.TWF_NODE_EVALUATE_CUSTOMER_DETAIL,
			com.yunat.ccms.jooq.tables.TwfNodeEvaluateOrderDetail.TWF_NODE_EVALUATE_ORDER_DETAIL,
			com.yunat.ccms.jooq.tables.TwfNodeEvaluateProductDetail.TWF_NODE_EVALUATE_PRODUCT_DETAIL,
			com.yunat.ccms.jooq.tables.TwfNodeQuery.TWF_NODE_QUERY,
			com.yunat.ccms.jooq.tables.TwfNodeQueryCriteria.TWF_NODE_QUERY_CRITERIA,
			com.yunat.ccms.jooq.tables.TwfNodeQueryDefined.TWF_NODE_QUERY_DEFINED,
			com.yunat.ccms.jooq.tables.TwfNodeRetry.TWF_NODE_RETRY,
			com.yunat.ccms.jooq.tables.TwfNodeSms.TWF_NODE_SMS,
			com.yunat.ccms.jooq.tables.TwfNodeSmsExecutionRecord.TWF_NODE_SMS_EXECUTION_RECORD,
			com.yunat.ccms.jooq.tables.TwfNodeSmsSampleRecord.TWF_NODE_SMS_SAMPLE_RECORD,
			com.yunat.ccms.jooq.tables.TwfNodeTarget.TWF_NODE_TARGET,
			com.yunat.ccms.jooq.tables.TwfNodeTime.TWF_NODE_TIME,
			com.yunat.ccms.jooq.tables.TwfNodeType.TWF_NODE_TYPE,
			com.yunat.ccms.jooq.tables.TwfNodeTypeGroup.TWF_NODE_TYPE_GROUP,
			com.yunat.ccms.jooq.tables.TwfNodeTypeMid2Toolbar.TWF_NODE_TYPE_MID2_TOOLBAR,
			com.yunat.ccms.jooq.tables.TwfNodeWait.TWF_NODE_WAIT,
			com.yunat.ccms.jooq.tables.TwfWorkflow.TWF_WORKFLOW,
			com.yunat.ccms.jooq.tables.TwfWorkflowNodeGroup.TWF_WORKFLOW_NODE_GROUP,
			com.yunat.ccms.jooq.tables.TwEmailBlacklist.TW_EMAIL_BLACKLIST,
			com.yunat.ccms.jooq.tables.TwEmailRedlist.TW_EMAIL_REDLIST,
			com.yunat.ccms.jooq.tables.TwMemberBlacklist.TW_MEMBER_BLACKLIST,
			com.yunat.ccms.jooq.tables.TwMobileBlacklist.TW_MOBILE_BLACKLIST,
			com.yunat.ccms.jooq.tables.TwMobileRedlist.TW_MOBILE_REDLIST,
			com.yunat.ccms.jooq.tables.UniCustomer.UNI_CUSTOMER,
			com.yunat.ccms.jooq.tables.UniCustomerPlat.UNI_CUSTOMER_PLAT,
			com.yunat.ccms.jooq.tables.UniPlat.UNI_PLAT,
			com.yunat.ccms.jooq.tables.VmTaobaoOrder.VM_TAOBAO_ORDER,
			com.yunat.ccms.jooq.tables.VwTaobaoCustomer.VW_TAOBAO_CUSTOMER);
	}
}
