/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>ccms</code> 
 * schema
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class Keys {

	// IDENTITY definitions
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_PLT_EXT_IMPORT_BATCH = Identities0.IDENTITY_PLT_EXT_IMPORT_BATCH;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_PLT_MODIFY_CUSTOMER_LOG = Identities0.IDENTITY_PLT_MODIFY_CUSTOMER_LOG;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TB_APP_PROPERTIES = Identities0.IDENTITY_TB_APP_PROPERTIES;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TB_CAMPAIGN = Identities0.IDENTITY_TB_CAMPAIGN;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TB_CAMP_INVESTIGATE_COMMENTS = Identities0.IDENTITY_TB_CAMP_INVESTIGATE_COMMENTS;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TB_CHANNEL = Identities0.IDENTITY_TB_CHANNEL;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TB_PROGRAM = Identities0.IDENTITY_TB_PROGRAM;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TB_REMOTE_LOG_EXCEPTION = Identities0.IDENTITY_TB_REMOTE_LOG_EXCEPTION;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TB_ROLE = Identities0.IDENTITY_TB_ROLE;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TB_SYSUSER = Identities0.IDENTITY_TB_SYSUSER;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TB_TEMPLATE = Identities0.IDENTITY_TB_TEMPLATE;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TDS_PERMISSION = Identities0.IDENTITY_TDS_PERMISSION;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TDU_PROG_TYPE = Identities0.IDENTITY_TDU_PROG_TYPE;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_CATALOG = Identities0.IDENTITY_TM_CATALOG;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_CATALOG_CRITERIA = Identities0.IDENTITY_TM_CATALOG_CRITERIA;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_DB_COLUMN = Identities0.IDENTITY_TM_DB_COLUMN;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_DB_TABLE = Identities0.IDENTITY_TM_DB_TABLE;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_DIC = Identities0.IDENTITY_TM_DIC;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_DIC_VALUE = Identities0.IDENTITY_TM_DIC_VALUE;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_QUERY = Identities0.IDENTITY_TM_QUERY;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_QUERY_COLUMN = Identities0.IDENTITY_TM_QUERY_COLUMN;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_QUERY_CRITERIA = Identities0.IDENTITY_TM_QUERY_CRITERIA;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_QUERY_JOIN_CRITERIA = Identities0.IDENTITY_TM_QUERY_JOIN_CRITERIA;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_QUERY_TABLE = Identities0.IDENTITY_TM_QUERY_TABLE;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_REFER = Identities0.IDENTITY_TM_REFER;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_CONNECT = Identities0.IDENTITY_TWF_CONNECT;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_LOG_CHANNEL = Identities0.IDENTITY_TWF_LOG_CHANNEL;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_LOG_JOB = Identities0.IDENTITY_TWF_LOG_JOB;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_LOG_SUBJOB = Identities0.IDENTITY_TWF_LOG_SUBJOB;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE = Identities0.IDENTITY_TWF_NODE;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_EVALUATE_CUSTOMER_DETAIL = Identities0.IDENTITY_TWF_NODE_EVALUATE_CUSTOMER_DETAIL;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_EVALUATE_ORDER_DETAIL = Identities0.IDENTITY_TWF_NODE_EVALUATE_ORDER_DETAIL;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_EVALUATE_PRODUCT_DETAIL = Identities0.IDENTITY_TWF_NODE_EVALUATE_PRODUCT_DETAIL;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_QUERY_CRITERIA = Identities0.IDENTITY_TWF_NODE_QUERY_CRITERIA;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_QUERY_DEFINED = Identities0.IDENTITY_TWF_NODE_QUERY_DEFINED;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_RETRY = Identities0.IDENTITY_TWF_NODE_RETRY;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_SMS_EXECUTION_RECORD = Identities0.IDENTITY_TWF_NODE_SMS_EXECUTION_RECORD;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_SMS_SAMPLE_RECORD = Identities0.IDENTITY_TWF_NODE_SMS_SAMPLE_RECORD;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_TYPE = Identities0.IDENTITY_TWF_NODE_TYPE;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_TYPE_GROUP = Identities0.IDENTITY_TWF_NODE_TYPE_GROUP;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_TYPE_MID2_TOOLBAR = Identities0.IDENTITY_TWF_NODE_TYPE_MID2_TOOLBAR;
	public static final org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_WORKFLOW = Identities0.IDENTITY_TWF_WORKFLOW;

	// UNIQUE and PRIMARY KEY definitions
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_EXTAOBAO_CUSTOMER_PRIMARY = UniqueKeys0.KEY_PLT_EXTAOBAO_CUSTOMER_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_EXT_BATCH_CUSTOMER_PRIMARY = UniqueKeys0.KEY_PLT_EXT_BATCH_CUSTOMER_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_EXT_CUSTOMER_PRIMARY = UniqueKeys0.KEY_PLT_EXT_CUSTOMER_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_EXT_IMPORT_BATCH_PRIMARY = UniqueKeys0.KEY_PLT_EXT_IMPORT_BATCH_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_KFGZT_CUSTOMER_PRIMARY = UniqueKeys0.KEY_PLT_KFGZT_CUSTOMER_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_KFGZT_CUSTOMER_LABEL_PRIMARY = UniqueKeys0.KEY_PLT_KFGZT_CUSTOMER_LABEL_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_KFGZT_SHOP_LABEL_PRIMARY = UniqueKeys0.KEY_PLT_KFGZT_SHOP_LABEL_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_MODIFY_CUSTOMER_PRIMARY = UniqueKeys0.KEY_PLT_MODIFY_CUSTOMER_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_MODIFY_CUSTOMER_LOG_PRIMARY = UniqueKeys0.KEY_PLT_MODIFY_CUSTOMER_LOG_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_COUPON_PRIMARY = UniqueKeys0.KEY_PLT_TAOBAO_COUPON_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_COUPON_DENOMINATION_PRIMARY = UniqueKeys0.KEY_PLT_TAOBAO_COUPON_DENOMINATION_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_CRM_MEMBER_PRIMARY = UniqueKeys0.KEY_PLT_TAOBAO_CRM_MEMBER_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_CUSTOMER_PRIMARY = UniqueKeys0.KEY_PLT_TAOBAO_CUSTOMER_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_ITEM_CAT_PRIMARY = UniqueKeys0.KEY_PLT_TAOBAO_ITEM_CAT_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_ITEM_PROP_PRIMARY = UniqueKeys0.KEY_PLT_TAOBAO_ITEM_PROP_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_ITEM_PROP_VAL_PRIMARY = UniqueKeys0.KEY_PLT_TAOBAO_ITEM_PROP_VAL_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_ITEM_SELLER_CAT_PRIMARY = UniqueKeys0.KEY_PLT_TAOBAO_ITEM_SELLER_CAT_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_ORDER_PRIMARY = UniqueKeys0.KEY_PLT_TAOBAO_ORDER_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_ORDER_ITEM_PRIMARY = UniqueKeys0.KEY_PLT_TAOBAO_ORDER_ITEM_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_ORDER_TYPE_PRIMARY = UniqueKeys0.KEY_PLT_TAOBAO_ORDER_TYPE_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_PAY_TYPE_PRIMARY = UniqueKeys0.KEY_PLT_TAOBAO_PAY_TYPE_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_PRODUCT_PRIMARY = UniqueKeys0.KEY_PLT_TAOBAO_PRODUCT_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_PRODUCT_PROP_PRIMARY = UniqueKeys0.KEY_PLT_TAOBAO_PRODUCT_PROP_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_PRODUCT_SELLER_CAT_PRIMARY = UniqueKeys0.KEY_PLT_TAOBAO_PRODUCT_SELLER_CAT_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_SHIPPING_PRIMARY = UniqueKeys0.KEY_PLT_TAOBAO_SHIPPING_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_SHOP_PRIMARY = UniqueKeys0.KEY_PLT_TAOBAO_SHOP_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_TARGET_TYPE_PRIMARY = UniqueKeys0.KEY_PLT_TAOBAO_TARGET_TYPE_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_TRADERATE_PRIMARY = UniqueKeys0.KEY_PLT_TAOBAO_TRADERATE_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_WDZX_CUSTOMER_PRIMARY = UniqueKeys0.KEY_PLT_WDZX_CUSTOMER_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_WDZX_EMAIL_SUBSCRIBE_PRIMARY = UniqueKeys0.KEY_PLT_WDZX_EMAIL_SUBSCRIBE_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_APP_EXPIRED_PRIMARY = UniqueKeys0.KEY_TB_APP_EXPIRED_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_APP_PROPERTIES_PRIMARY = UniqueKeys0.KEY_TB_APP_PROPERTIES_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_CAMPAIGN_PRIMARY = UniqueKeys0.KEY_TB_CAMPAIGN_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_CAMP_INVESTIGATE_COMMENTS_PRIMARY = UniqueKeys0.KEY_TB_CAMP_INVESTIGATE_COMMENTS_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_CHANNEL_PRIMARY = UniqueKeys0.KEY_TB_CHANNEL_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_FUNCTION_LIMIT_PRIMARY = UniqueKeys0.KEY_TB_FUNCTION_LIMIT_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_PROGRAM_PRIMARY = UniqueKeys0.KEY_TB_PROGRAM_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_REMOTE_LOG_EXCEPTION_PRIMARY = UniqueKeys0.KEY_TB_REMOTE_LOG_EXCEPTION_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_ROLE_PRIMARY = UniqueKeys0.KEY_TB_ROLE_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_ROLE_PERMISSION_PRIMARY = UniqueKeys0.KEY_TB_ROLE_PERMISSION_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_SYSUSER_PRIMARY = UniqueKeys0.KEY_TB_SYSUSER_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_SYSUSER_UK_TB_SYSUSER_LOGINNAME_USERTYPE = UniqueKeys0.KEY_TB_SYSUSER_UK_TB_SYSUSER_LOGINNAME_USERTYPE;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_SYS_TAOBAO_USER_PRIMARY = UniqueKeys0.KEY_TB_SYS_TAOBAO_USER_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_SYS_TAOBAO_USER_IDX_UNIQUE_PLAT_USER_ID = UniqueKeys0.KEY_TB_SYS_TAOBAO_USER_IDX_UNIQUE_PLAT_USER_ID;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_TEMPLATE_PRIMARY = UniqueKeys0.KEY_TB_TEMPLATE_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_USER_ROLE_PRIMARY = UniqueKeys0.KEY_TB_USER_ROLE_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TDS_CAMPAIGN_STATUS_PRIMARY = UniqueKeys0.KEY_TDS_CAMPAIGN_STATUS_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TDS_JOB_STATUS_PRIMARY = UniqueKeys0.KEY_TDS_JOB_STATUS_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TDS_ORDER_STATUS_PRIMARY = UniqueKeys0.KEY_TDS_ORDER_STATUS_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TDS_PERMISSION_PRIMARY = UniqueKeys0.KEY_TDS_PERMISSION_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TDS_SUBJOB_STATUS_PRIMARY = UniqueKeys0.KEY_TDS_SUBJOB_STATUS_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TDU_CAMPAIGN_CATEGORY_PRIMARY = UniqueKeys0.KEY_TDU_CAMPAIGN_CATEGORY_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TDU_PROG_TYPE_PRIMARY = UniqueKeys0.KEY_TDU_PROG_TYPE_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_CATALOG_PRIMARY = UniqueKeys0.KEY_TM_CATALOG_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_CATALOG_CRITERIA_PRIMARY = UniqueKeys0.KEY_TM_CATALOG_CRITERIA_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_DB_COLUMN_PRIMARY = UniqueKeys0.KEY_TM_DB_COLUMN_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_DB_TABLE_PRIMARY = UniqueKeys0.KEY_TM_DB_TABLE_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_DIC_PRIMARY = UniqueKeys0.KEY_TM_DIC_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_DIC_VALUE_PRIMARY = UniqueKeys0.KEY_TM_DIC_VALUE_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_QUERY_PRIMARY = UniqueKeys0.KEY_TM_QUERY_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_QUERY_COLUMN_PRIMARY = UniqueKeys0.KEY_TM_QUERY_COLUMN_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_QUERY_CRITERIA_PRIMARY = UniqueKeys0.KEY_TM_QUERY_CRITERIA_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_QUERY_JOIN_CRITERIA_PRIMARY = UniqueKeys0.KEY_TM_QUERY_JOIN_CRITERIA_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_QUERY_TABLE_PRIMARY = UniqueKeys0.KEY_TM_QUERY_TABLE_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_REFER_PRIMARY = UniqueKeys0.KEY_TM_REFER_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_CONNECT_PRIMARY = UniqueKeys0.KEY_TWF_CONNECT_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_LOG_CHANNEL_PRIMARY = UniqueKeys0.KEY_TWF_LOG_CHANNEL_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_LOG_GROUP_USER_PRIMARY = UniqueKeys0.KEY_TWF_LOG_GROUP_USER_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_LOG_JOB_PRIMARY = UniqueKeys0.KEY_TWF_LOG_JOB_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_LOG_SUBJOB_PRIMARY = UniqueKeys0.KEY_TWF_LOG_SUBJOB_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_LOG_SUBJOB_UK_TWF_LOG_SUBJOB_JOB_ID_NODE_ID = UniqueKeys0.KEY_TWF_LOG_SUBJOB_UK_TWF_LOG_SUBJOB_JOB_ID_NODE_ID;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_PRIMARY = UniqueKeys0.KEY_TWF_NODE_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_COUPON_PRIMARY = UniqueKeys0.KEY_TWF_NODE_COUPON_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_EVALUATE_PRIMARY = UniqueKeys0.KEY_TWF_NODE_EVALUATE_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_EVALUATE_CUSTOMER_DETAIL_PRIMARY = UniqueKeys0.KEY_TWF_NODE_EVALUATE_CUSTOMER_DETAIL_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_EVALUATE_ORDER_DETAIL_PRIMARY = UniqueKeys0.KEY_TWF_NODE_EVALUATE_ORDER_DETAIL_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_EVALUATE_PRODUCT_DETAIL_PRIMARY = UniqueKeys0.KEY_TWF_NODE_EVALUATE_PRODUCT_DETAIL_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_QUERY_PRIMARY = UniqueKeys0.KEY_TWF_NODE_QUERY_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_QUERY_CRITERIA_PRIMARY = UniqueKeys0.KEY_TWF_NODE_QUERY_CRITERIA_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_QUERY_DEFINED_PRIMARY = UniqueKeys0.KEY_TWF_NODE_QUERY_DEFINED_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_RETRY_PRIMARY = UniqueKeys0.KEY_TWF_NODE_RETRY_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_SMS_PRIMARY = UniqueKeys0.KEY_TWF_NODE_SMS_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_SMS_EXECUTION_RECORD_PRIMARY = UniqueKeys0.KEY_TWF_NODE_SMS_EXECUTION_RECORD_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_SMS_SAMPLE_RECORD_PRIMARY = UniqueKeys0.KEY_TWF_NODE_SMS_SAMPLE_RECORD_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_TARGET_PRIMARY = UniqueKeys0.KEY_TWF_NODE_TARGET_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_TIME_PRIMARY = UniqueKeys0.KEY_TWF_NODE_TIME_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_TYPE_PRIMARY = UniqueKeys0.KEY_TWF_NODE_TYPE_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_TYPE_GROUP_PRIMARY = UniqueKeys0.KEY_TWF_NODE_TYPE_GROUP_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_TYPE_MID2_TOOLBAR_PRIMARY = UniqueKeys0.KEY_TWF_NODE_TYPE_MID2_TOOLBAR_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_WAIT_PRIMARY = UniqueKeys0.KEY_TWF_NODE_WAIT_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_WORKFLOW_PRIMARY = UniqueKeys0.KEY_TWF_WORKFLOW_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_WORKFLOW_NODE_GROUP_PRIMARY = UniqueKeys0.KEY_TWF_WORKFLOW_NODE_GROUP_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TW_EMAIL_BLACKLIST_PRIMARY = UniqueKeys0.KEY_TW_EMAIL_BLACKLIST_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TW_EMAIL_REDLIST_PRIMARY = UniqueKeys0.KEY_TW_EMAIL_REDLIST_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TW_MEMBER_BLACKLIST_PRIMARY = UniqueKeys0.KEY_TW_MEMBER_BLACKLIST_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TW_MOBILE_BLACKLIST_PRIMARY = UniqueKeys0.KEY_TW_MOBILE_BLACKLIST_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TW_MOBILE_REDLIST_PRIMARY = UniqueKeys0.KEY_TW_MOBILE_REDLIST_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_UNI_CUSTOMER_PRIMARY = UniqueKeys0.KEY_UNI_CUSTOMER_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_UNI_CUSTOMER_PLAT_PRIMARY = UniqueKeys0.KEY_UNI_CUSTOMER_PLAT_PRIMARY;
	public static final org.jooq.UniqueKey<org.jooq.Record> KEY_UNI_PLAT_PRIMARY = UniqueKeys0.KEY_UNI_PLAT_PRIMARY;

	// FOREIGN KEY definitions

	/**
	 * No instances
	 */
	private Keys() {}

	@SuppressWarnings("hiding")
	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_PLT_EXT_IMPORT_BATCH = createIdentity(com.yunat.ccms.jooq.tables.PltExtImportBatch.PLT_EXT_IMPORT_BATCH, com.yunat.ccms.jooq.tables.PltExtImportBatch.PLT_EXT_IMPORT_BATCH.BATCH_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_PLT_MODIFY_CUSTOMER_LOG = createIdentity(com.yunat.ccms.jooq.tables.PltModifyCustomerLog.PLT_MODIFY_CUSTOMER_LOG, com.yunat.ccms.jooq.tables.PltModifyCustomerLog.PLT_MODIFY_CUSTOMER_LOG.LOG_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TB_APP_PROPERTIES = createIdentity(com.yunat.ccms.jooq.tables.TbAppProperties.TB_APP_PROPERTIES, com.yunat.ccms.jooq.tables.TbAppProperties.TB_APP_PROPERTIES.PROP_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TB_CAMPAIGN = createIdentity(com.yunat.ccms.jooq.tables.TbCampaign.TB_CAMPAIGN, com.yunat.ccms.jooq.tables.TbCampaign.TB_CAMPAIGN.CAMP_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TB_CAMP_INVESTIGATE_COMMENTS = createIdentity(com.yunat.ccms.jooq.tables.TbCampInvestigateComments.TB_CAMP_INVESTIGATE_COMMENTS, com.yunat.ccms.jooq.tables.TbCampInvestigateComments.TB_CAMP_INVESTIGATE_COMMENTS.COMMENTS_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TB_CHANNEL = createIdentity(com.yunat.ccms.jooq.tables.TbChannel.TB_CHANNEL, com.yunat.ccms.jooq.tables.TbChannel.TB_CHANNEL.CHANNEL_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TB_PROGRAM = createIdentity(com.yunat.ccms.jooq.tables.TbProgram.TB_PROGRAM, com.yunat.ccms.jooq.tables.TbProgram.TB_PROGRAM.PROG_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TB_REMOTE_LOG_EXCEPTION = createIdentity(com.yunat.ccms.jooq.tables.TbRemoteLogException.TB_REMOTE_LOG_EXCEPTION, com.yunat.ccms.jooq.tables.TbRemoteLogException.TB_REMOTE_LOG_EXCEPTION.EXCEPTION_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TB_ROLE = createIdentity(com.yunat.ccms.jooq.tables.TbRole.TB_ROLE, com.yunat.ccms.jooq.tables.TbRole.TB_ROLE.ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TB_SYSUSER = createIdentity(com.yunat.ccms.jooq.tables.TbSysuser.TB_SYSUSER, com.yunat.ccms.jooq.tables.TbSysuser.TB_SYSUSER.ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TB_TEMPLATE = createIdentity(com.yunat.ccms.jooq.tables.TbTemplate.TB_TEMPLATE, com.yunat.ccms.jooq.tables.TbTemplate.TB_TEMPLATE.TEMPLATE_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TDS_PERMISSION = createIdentity(com.yunat.ccms.jooq.tables.TdsPermission.TDS_PERMISSION, com.yunat.ccms.jooq.tables.TdsPermission.TDS_PERMISSION.ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TDU_PROG_TYPE = createIdentity(com.yunat.ccms.jooq.tables.TduProgType.TDU_PROG_TYPE, com.yunat.ccms.jooq.tables.TduProgType.TDU_PROG_TYPE.PROG_TYPE_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_CATALOG = createIdentity(com.yunat.ccms.jooq.tables.TmCatalog.TM_CATALOG, com.yunat.ccms.jooq.tables.TmCatalog.TM_CATALOG.CATALOG_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_CATALOG_CRITERIA = createIdentity(com.yunat.ccms.jooq.tables.TmCatalogCriteria.TM_CATALOG_CRITERIA, com.yunat.ccms.jooq.tables.TmCatalogCriteria.TM_CATALOG_CRITERIA.ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_DB_COLUMN = createIdentity(com.yunat.ccms.jooq.tables.TmDbColumn.TM_DB_COLUMN, com.yunat.ccms.jooq.tables.TmDbColumn.TM_DB_COLUMN.COLUMN_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_DB_TABLE = createIdentity(com.yunat.ccms.jooq.tables.TmDbTable.TM_DB_TABLE, com.yunat.ccms.jooq.tables.TmDbTable.TM_DB_TABLE.TABLE_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_DIC = createIdentity(com.yunat.ccms.jooq.tables.TmDic.TM_DIC, com.yunat.ccms.jooq.tables.TmDic.TM_DIC.DIC_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_DIC_VALUE = createIdentity(com.yunat.ccms.jooq.tables.TmDicValue.TM_DIC_VALUE, com.yunat.ccms.jooq.tables.TmDicValue.TM_DIC_VALUE.DIC_VALUE_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_QUERY = createIdentity(com.yunat.ccms.jooq.tables.TmQuery.TM_QUERY, com.yunat.ccms.jooq.tables.TmQuery.TM_QUERY.QUERY_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_QUERY_COLUMN = createIdentity(com.yunat.ccms.jooq.tables.TmQueryColumn.TM_QUERY_COLUMN, com.yunat.ccms.jooq.tables.TmQueryColumn.TM_QUERY_COLUMN.QUERY_COLUMN_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_QUERY_CRITERIA = createIdentity(com.yunat.ccms.jooq.tables.TmQueryCriteria.TM_QUERY_CRITERIA, com.yunat.ccms.jooq.tables.TmQueryCriteria.TM_QUERY_CRITERIA.QUERY_CRITERIA_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_QUERY_JOIN_CRITERIA = createIdentity(com.yunat.ccms.jooq.tables.TmQueryJoinCriteria.TM_QUERY_JOIN_CRITERIA, com.yunat.ccms.jooq.tables.TmQueryJoinCriteria.TM_QUERY_JOIN_CRITERIA.QUERY_JOIN_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_QUERY_TABLE = createIdentity(com.yunat.ccms.jooq.tables.TmQueryTable.TM_QUERY_TABLE, com.yunat.ccms.jooq.tables.TmQueryTable.TM_QUERY_TABLE.QUERY_TABLE_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TM_REFER = createIdentity(com.yunat.ccms.jooq.tables.TmRefer.TM_REFER, com.yunat.ccms.jooq.tables.TmRefer.TM_REFER.REFER_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_CONNECT = createIdentity(com.yunat.ccms.jooq.tables.TwfConnect.TWF_CONNECT, com.yunat.ccms.jooq.tables.TwfConnect.TWF_CONNECT.CONNECT_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_LOG_CHANNEL = createIdentity(com.yunat.ccms.jooq.tables.TwfLogChannel.TWF_LOG_CHANNEL, com.yunat.ccms.jooq.tables.TwfLogChannel.TWF_LOG_CHANNEL.ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_LOG_JOB = createIdentity(com.yunat.ccms.jooq.tables.TwfLogJob.TWF_LOG_JOB, com.yunat.ccms.jooq.tables.TwfLogJob.TWF_LOG_JOB.JOB_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_LOG_SUBJOB = createIdentity(com.yunat.ccms.jooq.tables.TwfLogSubjob.TWF_LOG_SUBJOB, com.yunat.ccms.jooq.tables.TwfLogSubjob.TWF_LOG_SUBJOB.SUBJOB_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE = createIdentity(com.yunat.ccms.jooq.tables.TwfNode.TWF_NODE, com.yunat.ccms.jooq.tables.TwfNode.TWF_NODE.NODE_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_EVALUATE_CUSTOMER_DETAIL = createIdentity(com.yunat.ccms.jooq.tables.TwfNodeEvaluateCustomerDetail.TWF_NODE_EVALUATE_CUSTOMER_DETAIL, com.yunat.ccms.jooq.tables.TwfNodeEvaluateCustomerDetail.TWF_NODE_EVALUATE_CUSTOMER_DETAIL.EVALUATE_CUSTOMER_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_EVALUATE_ORDER_DETAIL = createIdentity(com.yunat.ccms.jooq.tables.TwfNodeEvaluateOrderDetail.TWF_NODE_EVALUATE_ORDER_DETAIL, com.yunat.ccms.jooq.tables.TwfNodeEvaluateOrderDetail.TWF_NODE_EVALUATE_ORDER_DETAIL.EVALUATE_ORDER_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_EVALUATE_PRODUCT_DETAIL = createIdentity(com.yunat.ccms.jooq.tables.TwfNodeEvaluateProductDetail.TWF_NODE_EVALUATE_PRODUCT_DETAIL, com.yunat.ccms.jooq.tables.TwfNodeEvaluateProductDetail.TWF_NODE_EVALUATE_PRODUCT_DETAIL.EVALUATE_PRODUCT_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_QUERY_CRITERIA = createIdentity(com.yunat.ccms.jooq.tables.TwfNodeQueryCriteria.TWF_NODE_QUERY_CRITERIA, com.yunat.ccms.jooq.tables.TwfNodeQueryCriteria.TWF_NODE_QUERY_CRITERIA.NODE_CRITERIA_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_QUERY_DEFINED = createIdentity(com.yunat.ccms.jooq.tables.TwfNodeQueryDefined.TWF_NODE_QUERY_DEFINED, com.yunat.ccms.jooq.tables.TwfNodeQueryDefined.TWF_NODE_QUERY_DEFINED.QUERY_DEFINED_ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_RETRY = createIdentity(com.yunat.ccms.jooq.tables.TwfNodeRetry.TWF_NODE_RETRY, com.yunat.ccms.jooq.tables.TwfNodeRetry.TWF_NODE_RETRY.ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_SMS_EXECUTION_RECORD = createIdentity(com.yunat.ccms.jooq.tables.TwfNodeSmsExecutionRecord.TWF_NODE_SMS_EXECUTION_RECORD, com.yunat.ccms.jooq.tables.TwfNodeSmsExecutionRecord.TWF_NODE_SMS_EXECUTION_RECORD.ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_SMS_SAMPLE_RECORD = createIdentity(com.yunat.ccms.jooq.tables.TwfNodeSmsSampleRecord.TWF_NODE_SMS_SAMPLE_RECORD, com.yunat.ccms.jooq.tables.TwfNodeSmsSampleRecord.TWF_NODE_SMS_SAMPLE_RECORD.ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_TYPE = createIdentity(com.yunat.ccms.jooq.tables.TwfNodeType.TWF_NODE_TYPE, com.yunat.ccms.jooq.tables.TwfNodeType.TWF_NODE_TYPE.ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_TYPE_GROUP = createIdentity(com.yunat.ccms.jooq.tables.TwfNodeTypeGroup.TWF_NODE_TYPE_GROUP, com.yunat.ccms.jooq.tables.TwfNodeTypeGroup.TWF_NODE_TYPE_GROUP.ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_NODE_TYPE_MID2_TOOLBAR = createIdentity(com.yunat.ccms.jooq.tables.TwfNodeTypeMid2Toolbar.TWF_NODE_TYPE_MID2_TOOLBAR, com.yunat.ccms.jooq.tables.TwfNodeTypeMid2Toolbar.TWF_NODE_TYPE_MID2_TOOLBAR.ID);
		public static org.jooq.Identity<org.jooq.Record, java.lang.Long> IDENTITY_TWF_WORKFLOW = createIdentity(com.yunat.ccms.jooq.tables.TwfWorkflow.TWF_WORKFLOW, com.yunat.ccms.jooq.tables.TwfWorkflow.TWF_WORKFLOW.WORKFLOW_ID);
	}

	@SuppressWarnings({"hiding", "unchecked"})
	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_EXTAOBAO_CUSTOMER_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltExtaobaoCustomer.PLT_EXTAOBAO_CUSTOMER, com.yunat.ccms.jooq.tables.PltExtaobaoCustomer.PLT_EXTAOBAO_CUSTOMER.CUSTOMERNO);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_EXT_BATCH_CUSTOMER_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltExtBatchCustomer.PLT_EXT_BATCH_CUSTOMER, com.yunat.ccms.jooq.tables.PltExtBatchCustomer.PLT_EXT_BATCH_CUSTOMER.BATCH_ID, com.yunat.ccms.jooq.tables.PltExtBatchCustomer.PLT_EXT_BATCH_CUSTOMER.PLAT_CODE, com.yunat.ccms.jooq.tables.PltExtBatchCustomer.PLT_EXT_BATCH_CUSTOMER.CUSTOMERNO);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_EXT_CUSTOMER_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltExtCustomer.PLT_EXT_CUSTOMER, com.yunat.ccms.jooq.tables.PltExtCustomer.PLT_EXT_CUSTOMER.CUSTOMERNO);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_EXT_IMPORT_BATCH_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltExtImportBatch.PLT_EXT_IMPORT_BATCH, com.yunat.ccms.jooq.tables.PltExtImportBatch.PLT_EXT_IMPORT_BATCH.BATCH_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_KFGZT_CUSTOMER_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltKfgztCustomer.PLT_KFGZT_CUSTOMER, com.yunat.ccms.jooq.tables.PltKfgztCustomer.PLT_KFGZT_CUSTOMER.CUSTOMERNO);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_KFGZT_CUSTOMER_LABEL_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltKfgztCustomerLabel.PLT_KFGZT_CUSTOMER_LABEL, com.yunat.ccms.jooq.tables.PltKfgztCustomerLabel.PLT_KFGZT_CUSTOMER_LABEL.SHOP_NAME, com.yunat.ccms.jooq.tables.PltKfgztCustomerLabel.PLT_KFGZT_CUSTOMER_LABEL.CUSTOMERNO, com.yunat.ccms.jooq.tables.PltKfgztCustomerLabel.PLT_KFGZT_CUSTOMER_LABEL.LABEL_NAME);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_KFGZT_SHOP_LABEL_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltKfgztShopLabel.PLT_KFGZT_SHOP_LABEL, com.yunat.ccms.jooq.tables.PltKfgztShopLabel.PLT_KFGZT_SHOP_LABEL.SHOP_NAME, com.yunat.ccms.jooq.tables.PltKfgztShopLabel.PLT_KFGZT_SHOP_LABEL.LABEL_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_MODIFY_CUSTOMER_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltModifyCustomer.PLT_MODIFY_CUSTOMER, com.yunat.ccms.jooq.tables.PltModifyCustomer.PLT_MODIFY_CUSTOMER.CUSTOMERNO);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_MODIFY_CUSTOMER_LOG_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltModifyCustomerLog.PLT_MODIFY_CUSTOMER_LOG, com.yunat.ccms.jooq.tables.PltModifyCustomerLog.PLT_MODIFY_CUSTOMER_LOG.LOG_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_COUPON_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltTaobaoCoupon.PLT_TAOBAO_COUPON, com.yunat.ccms.jooq.tables.PltTaobaoCoupon.PLT_TAOBAO_COUPON.COUPON_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_COUPON_DENOMINATION_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltTaobaoCouponDenomination.PLT_TAOBAO_COUPON_DENOMINATION, com.yunat.ccms.jooq.tables.PltTaobaoCouponDenomination.PLT_TAOBAO_COUPON_DENOMINATION.DENOMINATION_VALUE);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_CRM_MEMBER_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltTaobaoCrmMember.PLT_TAOBAO_CRM_MEMBER, com.yunat.ccms.jooq.tables.PltTaobaoCrmMember.PLT_TAOBAO_CRM_MEMBER.DP_ID, com.yunat.ccms.jooq.tables.PltTaobaoCrmMember.PLT_TAOBAO_CRM_MEMBER.CUSTOMERNO);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_CUSTOMER_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltTaobaoCustomer.PLT_TAOBAO_CUSTOMER, com.yunat.ccms.jooq.tables.PltTaobaoCustomer.PLT_TAOBAO_CUSTOMER.CUSTOMERNO);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_ITEM_CAT_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltTaobaoItemCat.PLT_TAOBAO_ITEM_CAT, com.yunat.ccms.jooq.tables.PltTaobaoItemCat.PLT_TAOBAO_ITEM_CAT.CID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_ITEM_PROP_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltTaobaoItemProp.PLT_TAOBAO_ITEM_PROP, com.yunat.ccms.jooq.tables.PltTaobaoItemProp.PLT_TAOBAO_ITEM_PROP.PID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_ITEM_PROP_VAL_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltTaobaoItemPropVal.PLT_TAOBAO_ITEM_PROP_VAL, com.yunat.ccms.jooq.tables.PltTaobaoItemPropVal.PLT_TAOBAO_ITEM_PROP_VAL.CID, com.yunat.ccms.jooq.tables.PltTaobaoItemPropVal.PLT_TAOBAO_ITEM_PROP_VAL.PID, com.yunat.ccms.jooq.tables.PltTaobaoItemPropVal.PLT_TAOBAO_ITEM_PROP_VAL.VID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_ITEM_SELLER_CAT_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltTaobaoItemSellerCat.PLT_TAOBAO_ITEM_SELLER_CAT, com.yunat.ccms.jooq.tables.PltTaobaoItemSellerCat.PLT_TAOBAO_ITEM_SELLER_CAT.SELLER_CID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_ORDER_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltTaobaoOrder.PLT_TAOBAO_ORDER, com.yunat.ccms.jooq.tables.PltTaobaoOrder.PLT_TAOBAO_ORDER.TID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_ORDER_ITEM_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltTaobaoOrderItem.PLT_TAOBAO_ORDER_ITEM, com.yunat.ccms.jooq.tables.PltTaobaoOrderItem.PLT_TAOBAO_ORDER_ITEM.OID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_ORDER_TYPE_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltTaobaoOrderType.PLT_TAOBAO_ORDER_TYPE, com.yunat.ccms.jooq.tables.PltTaobaoOrderType.PLT_TAOBAO_ORDER_TYPE.TYPE);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_PAY_TYPE_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltTaobaoPayType.PLT_TAOBAO_PAY_TYPE, com.yunat.ccms.jooq.tables.PltTaobaoPayType.PLT_TAOBAO_PAY_TYPE.PAY_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_PRODUCT_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltTaobaoProduct.PLT_TAOBAO_PRODUCT, com.yunat.ccms.jooq.tables.PltTaobaoProduct.PLT_TAOBAO_PRODUCT.NUM_IID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_PRODUCT_PROP_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltTaobaoProductProp.PLT_TAOBAO_PRODUCT_PROP, com.yunat.ccms.jooq.tables.PltTaobaoProductProp.PLT_TAOBAO_PRODUCT_PROP.NUM_IID, com.yunat.ccms.jooq.tables.PltTaobaoProductProp.PLT_TAOBAO_PRODUCT_PROP.PID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_PRODUCT_SELLER_CAT_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltTaobaoProductSellerCat.PLT_TAOBAO_PRODUCT_SELLER_CAT, com.yunat.ccms.jooq.tables.PltTaobaoProductSellerCat.PLT_TAOBAO_PRODUCT_SELLER_CAT.NUM_IID, com.yunat.ccms.jooq.tables.PltTaobaoProductSellerCat.PLT_TAOBAO_PRODUCT_SELLER_CAT.SELLER_CID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_SHIPPING_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltTaobaoShipping.PLT_TAOBAO_SHIPPING, com.yunat.ccms.jooq.tables.PltTaobaoShipping.PLT_TAOBAO_SHIPPING.ORDER_CODE);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_SHOP_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltTaobaoShop.PLT_TAOBAO_SHOP, com.yunat.ccms.jooq.tables.PltTaobaoShop.PLT_TAOBAO_SHOP.SHOP_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_TARGET_TYPE_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltTaobaoTargetType.PLT_TAOBAO_TARGET_TYPE, com.yunat.ccms.jooq.tables.PltTaobaoTargetType.PLT_TAOBAO_TARGET_TYPE.TARGET_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_TAOBAO_TRADERATE_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltTaobaoTraderate.PLT_TAOBAO_TRADERATE, com.yunat.ccms.jooq.tables.PltTaobaoTraderate.PLT_TAOBAO_TRADERATE.TID, com.yunat.ccms.jooq.tables.PltTaobaoTraderate.PLT_TAOBAO_TRADERATE.OID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_WDZX_CUSTOMER_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltWdzxCustomer.PLT_WDZX_CUSTOMER, com.yunat.ccms.jooq.tables.PltWdzxCustomer.PLT_WDZX_CUSTOMER.CUSTOMERNO);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_PLT_WDZX_EMAIL_SUBSCRIBE_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.PltWdzxEmailSubscribe.PLT_WDZX_EMAIL_SUBSCRIBE, com.yunat.ccms.jooq.tables.PltWdzxEmailSubscribe.PLT_WDZX_EMAIL_SUBSCRIBE.DP_ID, com.yunat.ccms.jooq.tables.PltWdzxEmailSubscribe.PLT_WDZX_EMAIL_SUBSCRIBE.CUSTOMERNO);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_APP_EXPIRED_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TbAppExpired.TB_APP_EXPIRED, com.yunat.ccms.jooq.tables.TbAppExpired.TB_APP_EXPIRED.ASSOCIATE_USERNAME);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_APP_PROPERTIES_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TbAppProperties.TB_APP_PROPERTIES, com.yunat.ccms.jooq.tables.TbAppProperties.TB_APP_PROPERTIES.PROP_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_CAMPAIGN_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TbCampaign.TB_CAMPAIGN, com.yunat.ccms.jooq.tables.TbCampaign.TB_CAMPAIGN.CAMP_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_CAMP_INVESTIGATE_COMMENTS_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TbCampInvestigateComments.TB_CAMP_INVESTIGATE_COMMENTS, com.yunat.ccms.jooq.tables.TbCampInvestigateComments.TB_CAMP_INVESTIGATE_COMMENTS.COMMENTS_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_CHANNEL_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TbChannel.TB_CHANNEL, com.yunat.ccms.jooq.tables.TbChannel.TB_CHANNEL.CHANNEL_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_FUNCTION_LIMIT_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TbFunctionLimit.TB_FUNCTION_LIMIT, com.yunat.ccms.jooq.tables.TbFunctionLimit.TB_FUNCTION_LIMIT.ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_PROGRAM_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TbProgram.TB_PROGRAM, com.yunat.ccms.jooq.tables.TbProgram.TB_PROGRAM.PROG_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_REMOTE_LOG_EXCEPTION_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TbRemoteLogException.TB_REMOTE_LOG_EXCEPTION, com.yunat.ccms.jooq.tables.TbRemoteLogException.TB_REMOTE_LOG_EXCEPTION.EXCEPTION_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_ROLE_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TbRole.TB_ROLE, com.yunat.ccms.jooq.tables.TbRole.TB_ROLE.ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_ROLE_PERMISSION_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TbRolePermission.TB_ROLE_PERMISSION, com.yunat.ccms.jooq.tables.TbRolePermission.TB_ROLE_PERMISSION.ROLE_ID, com.yunat.ccms.jooq.tables.TbRolePermission.TB_ROLE_PERMISSION.PERMISSION_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_SYSUSER_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TbSysuser.TB_SYSUSER, com.yunat.ccms.jooq.tables.TbSysuser.TB_SYSUSER.ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_SYSUSER_UK_TB_SYSUSER_LOGINNAME_USERTYPE = createUniqueKey(com.yunat.ccms.jooq.tables.TbSysuser.TB_SYSUSER, com.yunat.ccms.jooq.tables.TbSysuser.TB_SYSUSER.LOGIN_NAME, com.yunat.ccms.jooq.tables.TbSysuser.TB_SYSUSER.USER_TYPE);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_SYS_TAOBAO_USER_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TbSysTaobaoUser.TB_SYS_TAOBAO_USER, com.yunat.ccms.jooq.tables.TbSysTaobaoUser.TB_SYS_TAOBAO_USER.ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_SYS_TAOBAO_USER_IDX_UNIQUE_PLAT_USER_ID = createUniqueKey(com.yunat.ccms.jooq.tables.TbSysTaobaoUser.TB_SYS_TAOBAO_USER, com.yunat.ccms.jooq.tables.TbSysTaobaoUser.TB_SYS_TAOBAO_USER.PLAT_USER_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_TEMPLATE_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TbTemplate.TB_TEMPLATE, com.yunat.ccms.jooq.tables.TbTemplate.TB_TEMPLATE.TEMPLATE_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TB_USER_ROLE_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TbUserRole.TB_USER_ROLE, com.yunat.ccms.jooq.tables.TbUserRole.TB_USER_ROLE.USER_ID, com.yunat.ccms.jooq.tables.TbUserRole.TB_USER_ROLE.ROLE_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TDS_CAMPAIGN_STATUS_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TdsCampaignStatus.TDS_CAMPAIGN_STATUS, com.yunat.ccms.jooq.tables.TdsCampaignStatus.TDS_CAMPAIGN_STATUS.STATUS_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TDS_JOB_STATUS_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TdsJobStatus.TDS_JOB_STATUS, com.yunat.ccms.jooq.tables.TdsJobStatus.TDS_JOB_STATUS.STATUS_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TDS_ORDER_STATUS_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TdsOrderStatus.TDS_ORDER_STATUS, com.yunat.ccms.jooq.tables.TdsOrderStatus.TDS_ORDER_STATUS.STATUS_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TDS_PERMISSION_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TdsPermission.TDS_PERMISSION, com.yunat.ccms.jooq.tables.TdsPermission.TDS_PERMISSION.ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TDS_SUBJOB_STATUS_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TdsSubjobStatus.TDS_SUBJOB_STATUS, com.yunat.ccms.jooq.tables.TdsSubjobStatus.TDS_SUBJOB_STATUS.STATUS_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TDU_CAMPAIGN_CATEGORY_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TduCampaignCategory.TDU_CAMPAIGN_CATEGORY, com.yunat.ccms.jooq.tables.TduCampaignCategory.TDU_CAMPAIGN_CATEGORY.CATEGORY_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TDU_PROG_TYPE_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TduProgType.TDU_PROG_TYPE, com.yunat.ccms.jooq.tables.TduProgType.TDU_PROG_TYPE.PROG_TYPE_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_CATALOG_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TmCatalog.TM_CATALOG, com.yunat.ccms.jooq.tables.TmCatalog.TM_CATALOG.CATALOG_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_CATALOG_CRITERIA_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TmCatalogCriteria.TM_CATALOG_CRITERIA, com.yunat.ccms.jooq.tables.TmCatalogCriteria.TM_CATALOG_CRITERIA.ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_DB_COLUMN_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TmDbColumn.TM_DB_COLUMN, com.yunat.ccms.jooq.tables.TmDbColumn.TM_DB_COLUMN.COLUMN_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_DB_TABLE_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TmDbTable.TM_DB_TABLE, com.yunat.ccms.jooq.tables.TmDbTable.TM_DB_TABLE.TABLE_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_DIC_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TmDic.TM_DIC, com.yunat.ccms.jooq.tables.TmDic.TM_DIC.DIC_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_DIC_VALUE_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TmDicValue.TM_DIC_VALUE, com.yunat.ccms.jooq.tables.TmDicValue.TM_DIC_VALUE.DIC_VALUE_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_QUERY_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TmQuery.TM_QUERY, com.yunat.ccms.jooq.tables.TmQuery.TM_QUERY.QUERY_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_QUERY_COLUMN_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TmQueryColumn.TM_QUERY_COLUMN, com.yunat.ccms.jooq.tables.TmQueryColumn.TM_QUERY_COLUMN.QUERY_COLUMN_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_QUERY_CRITERIA_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TmQueryCriteria.TM_QUERY_CRITERIA, com.yunat.ccms.jooq.tables.TmQueryCriteria.TM_QUERY_CRITERIA.QUERY_CRITERIA_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_QUERY_JOIN_CRITERIA_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TmQueryJoinCriteria.TM_QUERY_JOIN_CRITERIA, com.yunat.ccms.jooq.tables.TmQueryJoinCriteria.TM_QUERY_JOIN_CRITERIA.QUERY_JOIN_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_QUERY_TABLE_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TmQueryTable.TM_QUERY_TABLE, com.yunat.ccms.jooq.tables.TmQueryTable.TM_QUERY_TABLE.QUERY_TABLE_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TM_REFER_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TmRefer.TM_REFER, com.yunat.ccms.jooq.tables.TmRefer.TM_REFER.REFER_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_CONNECT_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfConnect.TWF_CONNECT, com.yunat.ccms.jooq.tables.TwfConnect.TWF_CONNECT.CONNECT_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_LOG_CHANNEL_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfLogChannel.TWF_LOG_CHANNEL, com.yunat.ccms.jooq.tables.TwfLogChannel.TWF_LOG_CHANNEL.ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_LOG_GROUP_USER_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfLogGroupUser.TWF_LOG_GROUP_USER, com.yunat.ccms.jooq.tables.TwfLogGroupUser.TWF_LOG_GROUP_USER.SUBJOB_ID, com.yunat.ccms.jooq.tables.TwfLogGroupUser.TWF_LOG_GROUP_USER.UNI_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_LOG_JOB_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfLogJob.TWF_LOG_JOB, com.yunat.ccms.jooq.tables.TwfLogJob.TWF_LOG_JOB.JOB_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_LOG_SUBJOB_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfLogSubjob.TWF_LOG_SUBJOB, com.yunat.ccms.jooq.tables.TwfLogSubjob.TWF_LOG_SUBJOB.SUBJOB_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_LOG_SUBJOB_UK_TWF_LOG_SUBJOB_JOB_ID_NODE_ID = createUniqueKey(com.yunat.ccms.jooq.tables.TwfLogSubjob.TWF_LOG_SUBJOB, com.yunat.ccms.jooq.tables.TwfLogSubjob.TWF_LOG_SUBJOB.JOB_ID, com.yunat.ccms.jooq.tables.TwfLogSubjob.TWF_LOG_SUBJOB.NODE_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfNode.TWF_NODE, com.yunat.ccms.jooq.tables.TwfNode.TWF_NODE.NODE_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_COUPON_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfNodeCoupon.TWF_NODE_COUPON, com.yunat.ccms.jooq.tables.TwfNodeCoupon.TWF_NODE_COUPON.NODE_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_EVALUATE_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfNodeEvaluate.TWF_NODE_EVALUATE, com.yunat.ccms.jooq.tables.TwfNodeEvaluate.TWF_NODE_EVALUATE.NODE_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_EVALUATE_CUSTOMER_DETAIL_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfNodeEvaluateCustomerDetail.TWF_NODE_EVALUATE_CUSTOMER_DETAIL, com.yunat.ccms.jooq.tables.TwfNodeEvaluateCustomerDetail.TWF_NODE_EVALUATE_CUSTOMER_DETAIL.EVALUATE_CUSTOMER_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_EVALUATE_ORDER_DETAIL_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfNodeEvaluateOrderDetail.TWF_NODE_EVALUATE_ORDER_DETAIL, com.yunat.ccms.jooq.tables.TwfNodeEvaluateOrderDetail.TWF_NODE_EVALUATE_ORDER_DETAIL.EVALUATE_ORDER_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_EVALUATE_PRODUCT_DETAIL_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfNodeEvaluateProductDetail.TWF_NODE_EVALUATE_PRODUCT_DETAIL, com.yunat.ccms.jooq.tables.TwfNodeEvaluateProductDetail.TWF_NODE_EVALUATE_PRODUCT_DETAIL.EVALUATE_PRODUCT_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_QUERY_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfNodeQuery.TWF_NODE_QUERY, com.yunat.ccms.jooq.tables.TwfNodeQuery.TWF_NODE_QUERY.NODE_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_QUERY_CRITERIA_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfNodeQueryCriteria.TWF_NODE_QUERY_CRITERIA, com.yunat.ccms.jooq.tables.TwfNodeQueryCriteria.TWF_NODE_QUERY_CRITERIA.NODE_CRITERIA_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_QUERY_DEFINED_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfNodeQueryDefined.TWF_NODE_QUERY_DEFINED, com.yunat.ccms.jooq.tables.TwfNodeQueryDefined.TWF_NODE_QUERY_DEFINED.QUERY_DEFINED_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_RETRY_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfNodeRetry.TWF_NODE_RETRY, com.yunat.ccms.jooq.tables.TwfNodeRetry.TWF_NODE_RETRY.ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_SMS_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfNodeSms.TWF_NODE_SMS, com.yunat.ccms.jooq.tables.TwfNodeSms.TWF_NODE_SMS.NODE_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_SMS_EXECUTION_RECORD_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfNodeSmsExecutionRecord.TWF_NODE_SMS_EXECUTION_RECORD, com.yunat.ccms.jooq.tables.TwfNodeSmsExecutionRecord.TWF_NODE_SMS_EXECUTION_RECORD.ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_SMS_SAMPLE_RECORD_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfNodeSmsSampleRecord.TWF_NODE_SMS_SAMPLE_RECORD, com.yunat.ccms.jooq.tables.TwfNodeSmsSampleRecord.TWF_NODE_SMS_SAMPLE_RECORD.ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_TARGET_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfNodeTarget.TWF_NODE_TARGET, com.yunat.ccms.jooq.tables.TwfNodeTarget.TWF_NODE_TARGET.NODE_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_TIME_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfNodeTime.TWF_NODE_TIME, com.yunat.ccms.jooq.tables.TwfNodeTime.TWF_NODE_TIME.NODE_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_TYPE_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfNodeType.TWF_NODE_TYPE, com.yunat.ccms.jooq.tables.TwfNodeType.TWF_NODE_TYPE.ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_TYPE_GROUP_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfNodeTypeGroup.TWF_NODE_TYPE_GROUP, com.yunat.ccms.jooq.tables.TwfNodeTypeGroup.TWF_NODE_TYPE_GROUP.ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_TYPE_MID2_TOOLBAR_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfNodeTypeMid2Toolbar.TWF_NODE_TYPE_MID2_TOOLBAR, com.yunat.ccms.jooq.tables.TwfNodeTypeMid2Toolbar.TWF_NODE_TYPE_MID2_TOOLBAR.ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_NODE_WAIT_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfNodeWait.TWF_NODE_WAIT, com.yunat.ccms.jooq.tables.TwfNodeWait.TWF_NODE_WAIT.NODE_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_WORKFLOW_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfWorkflow.TWF_WORKFLOW, com.yunat.ccms.jooq.tables.TwfWorkflow.TWF_WORKFLOW.WORKFLOW_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TWF_WORKFLOW_NODE_GROUP_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwfWorkflowNodeGroup.TWF_WORKFLOW_NODE_GROUP, com.yunat.ccms.jooq.tables.TwfWorkflowNodeGroup.TWF_WORKFLOW_NODE_GROUP.ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TW_EMAIL_BLACKLIST_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwEmailBlacklist.TW_EMAIL_BLACKLIST, com.yunat.ccms.jooq.tables.TwEmailBlacklist.TW_EMAIL_BLACKLIST.EMAIL);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TW_EMAIL_REDLIST_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwEmailRedlist.TW_EMAIL_REDLIST, com.yunat.ccms.jooq.tables.TwEmailRedlist.TW_EMAIL_REDLIST.EMAIL);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TW_MEMBER_BLACKLIST_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwMemberBlacklist.TW_MEMBER_BLACKLIST, com.yunat.ccms.jooq.tables.TwMemberBlacklist.TW_MEMBER_BLACKLIST.CUSTOMERNO);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TW_MOBILE_BLACKLIST_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwMobileBlacklist.TW_MOBILE_BLACKLIST, com.yunat.ccms.jooq.tables.TwMobileBlacklist.TW_MOBILE_BLACKLIST.MOBILE);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_TW_MOBILE_REDLIST_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.TwMobileRedlist.TW_MOBILE_REDLIST, com.yunat.ccms.jooq.tables.TwMobileRedlist.TW_MOBILE_REDLIST.MOBILE);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_UNI_CUSTOMER_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.UniCustomer.UNI_CUSTOMER, com.yunat.ccms.jooq.tables.UniCustomer.UNI_CUSTOMER.UNI_ID);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_UNI_CUSTOMER_PLAT_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.UniCustomerPlat.UNI_CUSTOMER_PLAT, com.yunat.ccms.jooq.tables.UniCustomerPlat.UNI_CUSTOMER_PLAT.PLAT_CODE, com.yunat.ccms.jooq.tables.UniCustomerPlat.UNI_CUSTOMER_PLAT.CUSTOMERNO);
		public static final org.jooq.UniqueKey<org.jooq.Record> KEY_UNI_PLAT_PRIMARY = createUniqueKey(com.yunat.ccms.jooq.tables.UniPlat.UNI_PLAT, com.yunat.ccms.jooq.tables.UniPlat.UNI_PLAT.PLAT_CODE);
	}
}
