/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in ccms
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public final class Tables {

	/**
	 * 外部导入客户信息（来源于“淘宝”平台）
	 */
	public static final com.yunat.ccms.jooq.tables.PltExtaobaoCustomer PLT_EXTAOBAO_CUSTOMER = com.yunat.ccms.jooq.tables.PltExtaobaoCustomer.PLT_EXTAOBAO_CUSTOMER;

	/**
	 * The table ccms.plt_ext_batch_customer
	 */
	public static final com.yunat.ccms.jooq.tables.PltExtBatchCustomer PLT_EXT_BATCH_CUSTOMER = com.yunat.ccms.jooq.tables.PltExtBatchCustomer.PLT_EXT_BATCH_CUSTOMER;

	/**
	 * 外部导入客户信息（非接驳平台）
	 */
	public static final com.yunat.ccms.jooq.tables.PltExtCustomer PLT_EXT_CUSTOMER = com.yunat.ccms.jooq.tables.PltExtCustomer.PLT_EXT_CUSTOMER;

	/**
	 * 外部导入客户批次信息表
	 */
	public static final com.yunat.ccms.jooq.tables.PltExtImportBatch PLT_EXT_IMPORT_BATCH = com.yunat.ccms.jooq.tables.PltExtImportBatch.PLT_EXT_IMPORT_BATCH;

	/**
	 * “客服工作台”同步客户信息
	 */
	public static final com.yunat.ccms.jooq.tables.PltKfgztCustomer PLT_KFGZT_CUSTOMER = com.yunat.ccms.jooq.tables.PltKfgztCustomer.PLT_KFGZT_CUSTOMER;

	/**
	 * “客服工作台”客户标签数据表
	 */
	public static final com.yunat.ccms.jooq.tables.PltKfgztCustomerLabel PLT_KFGZT_CUSTOMER_LABEL = com.yunat.ccms.jooq.tables.PltKfgztCustomerLabel.PLT_KFGZT_CUSTOMER_LABEL;

	/**
	 * “客服工作台”店铺签字典表
	 */
	public static final com.yunat.ccms.jooq.tables.PltKfgztShopLabel PLT_KFGZT_SHOP_LABEL = com.yunat.ccms.jooq.tables.PltKfgztShopLabel.PLT_KFGZT_SHOP_LABEL;

	/**
	 * 手工修改的统一客户信息表
	 */
	public static final com.yunat.ccms.jooq.tables.PltModifyCustomer PLT_MODIFY_CUSTOMER = com.yunat.ccms.jooq.tables.PltModifyCustomer.PLT_MODIFY_CUSTOMER;

	/**
	 * 手工修改的统一客户信息表
	 */
	public static final com.yunat.ccms.jooq.tables.PltModifyCustomerLog PLT_MODIFY_CUSTOMER_LOG = com.yunat.ccms.jooq.tables.PltModifyCustomerLog.PLT_MODIFY_CUSTOMER_LOG;

	/**
	 * 淘宝优惠券信息表
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoCoupon PLT_TAOBAO_COUPON = com.yunat.ccms.jooq.tables.PltTaobaoCoupon.PLT_TAOBAO_COUPON;

	/**
	 * 淘宝优惠券面额字典表
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoCouponDenomination PLT_TAOBAO_COUPON_DENOMINATION = com.yunat.ccms.jooq.tables.PltTaobaoCouponDenomination.PLT_TAOBAO_COUPON_DENOMINATION;

	/**
	 * 店铺买家会员信息表
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoCrmMember PLT_TAOBAO_CRM_MEMBER = com.yunat.ccms.jooq.tables.PltTaobaoCrmMember.PLT_TAOBAO_CRM_MEMBER;

	/**
	 * 客户信息表
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoCustomer PLT_TAOBAO_CUSTOMER = com.yunat.ccms.jooq.tables.PltTaobaoCustomer.PLT_TAOBAO_CUSTOMER;

	/**
	 * 商品类目
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoItemCat PLT_TAOBAO_ITEM_CAT = com.yunat.ccms.jooq.tables.PltTaobaoItemCat.PLT_TAOBAO_ITEM_CAT;

	/**
	 * 商品属性
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoItemProp PLT_TAOBAO_ITEM_PROP = com.yunat.ccms.jooq.tables.PltTaobaoItemProp.PLT_TAOBAO_ITEM_PROP;

	/**
	 * 商品属性值
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoItemPropVal PLT_TAOBAO_ITEM_PROP_VAL = com.yunat.ccms.jooq.tables.PltTaobaoItemPropVal.PLT_TAOBAO_ITEM_PROP_VAL;

	/**
	 * 卖家自定义类目
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoItemSellerCat PLT_TAOBAO_ITEM_SELLER_CAT = com.yunat.ccms.jooq.tables.PltTaobaoItemSellerCat.PLT_TAOBAO_ITEM_SELLER_CAT;

	/**
	 * 订单表
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoOrder PLT_TAOBAO_ORDER = com.yunat.ccms.jooq.tables.PltTaobaoOrder.PLT_TAOBAO_ORDER;

	/**
	 * 订单明细表（子订单/商品明细）
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoOrderItem PLT_TAOBAO_ORDER_ITEM = com.yunat.ccms.jooq.tables.PltTaobaoOrderItem.PLT_TAOBAO_ORDER_ITEM;

	/**
	 * 淘宝订单交易类型
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoOrderType PLT_TAOBAO_ORDER_TYPE = com.yunat.ccms.jooq.tables.PltTaobaoOrderType.PLT_TAOBAO_ORDER_TYPE;

	/**
	 * 零售版支付类型的数据字典表
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoPayType PLT_TAOBAO_PAY_TYPE = com.yunat.ccms.jooq.tables.PltTaobaoPayType.PLT_TAOBAO_PAY_TYPE;

	/**
	 * 淘宝商品表
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoProduct PLT_TAOBAO_PRODUCT = com.yunat.ccms.jooq.tables.PltTaobaoProduct.PLT_TAOBAO_PRODUCT;

	/**
	 * 商品对应的商品属性
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoProductProp PLT_TAOBAO_PRODUCT_PROP = com.yunat.ccms.jooq.tables.PltTaobaoProductProp.PLT_TAOBAO_PRODUCT_PROP;

	/**
	 * 商品对应的卖家自定义类目
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoProductSellerCat PLT_TAOBAO_PRODUCT_SELLER_CAT = com.yunat.ccms.jooq.tables.PltTaobaoProductSellerCat.PLT_TAOBAO_PRODUCT_SELLER_CAT;

	/**
	 * 淘宝物流运单
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoShipping PLT_TAOBAO_SHIPPING = com.yunat.ccms.jooq.tables.PltTaobaoShipping.PLT_TAOBAO_SHIPPING;

	/**
	 * 淘宝店铺信息表
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoShop PLT_TAOBAO_SHOP = com.yunat.ccms.jooq.tables.PltTaobaoShop.PLT_TAOBAO_SHOP;

	/**
	 * 订单查询的客户汇总指标字典表
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoTargetType PLT_TAOBAO_TARGET_TYPE = com.yunat.ccms.jooq.tables.PltTaobaoTargetType.PLT_TAOBAO_TARGET_TYPE;

	/**
	 * 交易评价信息
	 */
	public static final com.yunat.ccms.jooq.tables.PltTaobaoTraderate PLT_TAOBAO_TRADERATE = com.yunat.ccms.jooq.tables.PltTaobaoTraderate.PLT_TAOBAO_TRADERATE;

	/**
	 * “我的中心”同步客户信息
	 */
	public static final com.yunat.ccms.jooq.tables.PltWdzxCustomer PLT_WDZX_CUSTOMER = com.yunat.ccms.jooq.tables.PltWdzxCustomer.PLT_WDZX_CUSTOMER;

	/**
	 * “我的中心”店铺邮件订阅用户表
	 */
	public static final com.yunat.ccms.jooq.tables.PltWdzxEmailSubscribe PLT_WDZX_EMAIL_SUBSCRIBE = com.yunat.ccms.jooq.tables.PltWdzxEmailSubscribe.PLT_WDZX_EMAIL_SUBSCRIBE;

	/**
	 * 应用订购期
	 */
	public static final com.yunat.ccms.jooq.tables.TbAppExpired TB_APP_EXPIRED = com.yunat.ccms.jooq.tables.TbAppExpired.TB_APP_EXPIRED;

	/**
	 * 应用级属性参数配置表
	 */
	public static final com.yunat.ccms.jooq.tables.TbAppProperties TB_APP_PROPERTIES = com.yunat.ccms.jooq.tables.TbAppProperties.TB_APP_PROPERTIES;

	/**
	 * 活动的基本信息表
	 */
	public static final com.yunat.ccms.jooq.tables.TbCampaign TB_CAMPAIGN = com.yunat.ccms.jooq.tables.TbCampaign.TB_CAMPAIGN;

	/**
	 * 活动的审批的备注
	 */
	public static final com.yunat.ccms.jooq.tables.TbCampInvestigateComments TB_CAMP_INVESTIGATE_COMMENTS = com.yunat.ccms.jooq.tables.TbCampInvestigateComments.TB_CAMP_INVESTIGATE_COMMENTS;

	/**
	 * 渠道表
	 */
	public static final com.yunat.ccms.jooq.tables.TbChannel TB_CHANNEL = com.yunat.ccms.jooq.tables.TbChannel.TB_CHANNEL;

	/**
	 * 系统功能限制
	 */
	public static final com.yunat.ccms.jooq.tables.TbFunctionLimit TB_FUNCTION_LIMIT = com.yunat.ccms.jooq.tables.TbFunctionLimit.TB_FUNCTION_LIMIT;

	/**
	 * 沟通项目表
	 */
	public static final com.yunat.ccms.jooq.tables.TbProgram TB_PROGRAM = com.yunat.ccms.jooq.tables.TbProgram.TB_PROGRAM;

	/**
	 * 访问异常日志表
	 */
	public static final com.yunat.ccms.jooq.tables.TbRemoteLogException TB_REMOTE_LOG_EXCEPTION = com.yunat.ccms.jooq.tables.TbRemoteLogException.TB_REMOTE_LOG_EXCEPTION;

	/**
	 * 系统用户角色表
	 */
	public static final com.yunat.ccms.jooq.tables.TbRole TB_ROLE = com.yunat.ccms.jooq.tables.TbRole.TB_ROLE;

	/**
	 * 系统用户角色－权限关系表
	 */
	public static final com.yunat.ccms.jooq.tables.TbRolePermission TB_ROLE_PERMISSION = com.yunat.ccms.jooq.tables.TbRolePermission.TB_ROLE_PERMISSION;

	/**
	 * 系统用户表
	 */
	public static final com.yunat.ccms.jooq.tables.TbSysuser TB_SYSUSER = com.yunat.ccms.jooq.tables.TbSysuser.TB_SYSUSER;

	/**
	 * The table ccms.tb_sys_taobao_user
	 */
	public static final com.yunat.ccms.jooq.tables.TbSysTaobaoUser TB_SYS_TAOBAO_USER = com.yunat.ccms.jooq.tables.TbSysTaobaoUser.TB_SYS_TAOBAO_USER;

	/**
	 * 活动模板表
	 */
	public static final com.yunat.ccms.jooq.tables.TbTemplate TB_TEMPLATE = com.yunat.ccms.jooq.tables.TbTemplate.TB_TEMPLATE;

	/**
	 * The table ccms.tb_user_role
	 */
	public static final com.yunat.ccms.jooq.tables.TbUserRole TB_USER_ROLE = com.yunat.ccms.jooq.tables.TbUserRole.TB_USER_ROLE;

	/**
	 * 活动状态表
	 */
	public static final com.yunat.ccms.jooq.tables.TdsCampaignStatus TDS_CAMPAIGN_STATUS = com.yunat.ccms.jooq.tables.TdsCampaignStatus.TDS_CAMPAIGN_STATUS;

	/**
	 * 任务状态维表
	 */
	public static final com.yunat.ccms.jooq.tables.TdsJobStatus TDS_JOB_STATUS = com.yunat.ccms.jooq.tables.TdsJobStatus.TDS_JOB_STATUS;

	/**
	 * CCMS订单状态维表
	 */
	public static final com.yunat.ccms.jooq.tables.TdsOrderStatus TDS_ORDER_STATUS = com.yunat.ccms.jooq.tables.TdsOrderStatus.TDS_ORDER_STATUS;

	/**
	 * The table ccms.tds_permission
	 */
	public static final com.yunat.ccms.jooq.tables.TdsPermission TDS_PERMISSION = com.yunat.ccms.jooq.tables.TdsPermission.TDS_PERMISSION;

	/**
	 * 子任务状态维表
	 */
	public static final com.yunat.ccms.jooq.tables.TdsSubjobStatus TDS_SUBJOB_STATUS = com.yunat.ccms.jooq.tables.TdsSubjobStatus.TDS_SUBJOB_STATUS;

	/**
	 * 活动类型表
	 */
	public static final com.yunat.ccms.jooq.tables.TduCampaignCategory TDU_CAMPAIGN_CATEGORY = com.yunat.ccms.jooq.tables.TduCampaignCategory.TDU_CAMPAIGN_CATEGORY;

	/**
	 * 项目类型字典表
	 */
	public static final com.yunat.ccms.jooq.tables.TduProgType TDU_PROG_TYPE = com.yunat.ccms.jooq.tables.TduProgType.TDU_PROG_TYPE;

	/**
	 * 查询索引：原来的tm_view_dir表
	 */
	public static final com.yunat.ccms.jooq.tables.TmCatalog TM_CATALOG = com.yunat.ccms.jooq.tables.TmCatalog.TM_CATALOG;

	/**
	 * 索引和查询属性的多对多关联，可以重新定义显示名称和显示顺序
	 */
	public static final com.yunat.ccms.jooq.tables.TmCatalogCriteria TM_CATALOG_CRITERIA = com.yunat.ccms.jooq.tables.TmCatalogCriteria.TM_CATALOG_CRITERIA;

	/**
	 * 物理表字段定义
	 */
	public static final com.yunat.ccms.jooq.tables.TmDbColumn TM_DB_COLUMN = com.yunat.ccms.jooq.tables.TmDbColumn.TM_DB_COLUMN;

	/**
	 * 物理表定义
	 */
	public static final com.yunat.ccms.jooq.tables.TmDbTable TM_DB_TABLE = com.yunat.ccms.jooq.tables.TmDbTable.TM_DB_TABLE;

	/**
	 * 普通字典类型表
	 */
	public static final com.yunat.ccms.jooq.tables.TmDic TM_DIC = com.yunat.ccms.jooq.tables.TmDic.TM_DIC;

	/**
	 * 字典类型枚举值表
	 */
	public static final com.yunat.ccms.jooq.tables.TmDicValue TM_DIC_VALUE = com.yunat.ccms.jooq.tables.TmDicValue.TM_DIC_VALUE;

	/**
	 * 查询模版，代表一个查询的结构，但是查询条件尚未明确，需要用户保存查询条件
	 */
	public static final com.yunat.ccms.jooq.tables.TmQuery TM_QUERY = com.yunat.ccms.jooq.tables.TmQuery.TM_QUERY;

	/**
	 * 查询模版的字段
	 */
	public static final com.yunat.ccms.jooq.tables.TmQueryColumn TM_QUERY_COLUMN = com.yunat.ccms.jooq.tables.TmQueryColumn.TM_QUERY_COLUMN;

	/**
	 * 查询属性
	 */
	public static final com.yunat.ccms.jooq.tables.TmQueryCriteria TM_QUERY_CRITERIA = com.yunat.ccms.jooq.tables.TmQueryCriteria.TM_QUERY_CRITERIA;

	/**
	 * 查询where部分定义，也包含groupby 和 having
	 */
	public static final com.yunat.ccms.jooq.tables.TmQueryJoinCriteria TM_QUERY_JOIN_CRITERIA = com.yunat.ccms.jooq.tables.TmQueryJoinCriteria.TM_QUERY_JOIN_CRITERIA;

	/**
	 * 查询模版包含的查询表
	 */
	public static final com.yunat.ccms.jooq.tables.TmQueryTable TM_QUERY_TABLE = com.yunat.ccms.jooq.tables.TmQueryTable.TM_QUERY_TABLE;

	/**
	 * 关联类型的字典
	 */
	public static final com.yunat.ccms.jooq.tables.TmRefer TM_REFER = com.yunat.ccms.jooq.tables.TmRefer.TM_REFER;

	/**
	 * 流程的连接信息表
	 */
	public static final com.yunat.ccms.jooq.tables.TwfConnect TWF_CONNECT = com.yunat.ccms.jooq.tables.TwfConnect.TWF_CONNECT;

	/**
	 * 渠道执行日志表
	 */
	public static final com.yunat.ccms.jooq.tables.TwfLogChannel TWF_LOG_CHANNEL = com.yunat.ccms.jooq.tables.TwfLogChannel.TWF_LOG_CHANNEL;

	/**
	 * 用户渠道沟通日志表
	 */
	public static final com.yunat.ccms.jooq.tables.TwfLogChannelUser TWF_LOG_CHANNEL_USER = com.yunat.ccms.jooq.tables.TwfLogChannelUser.TWF_LOG_CHANNEL_USER;

	/**
	 * 活动执行用户组列表
	 */
	public static final com.yunat.ccms.jooq.tables.TwfLogGroup TWF_LOG_GROUP = com.yunat.ccms.jooq.tables.TwfLogGroup.TWF_LOG_GROUP;

	/**
	 * 活动执行用户组用户 (subjob_id每隔10000就建立一个新的分区)
	 */
	public static final com.yunat.ccms.jooq.tables.TwfLogGroupUser TWF_LOG_GROUP_USER = com.yunat.ccms.jooq.tables.TwfLogGroupUser.TWF_LOG_GROUP_USER;

	/**
	 * 活动执行总表
	 */
	public static final com.yunat.ccms.jooq.tables.TwfLogJob TWF_LOG_JOB = com.yunat.ccms.jooq.tables.TwfLogJob.TWF_LOG_JOB;

	/**
	 * 流程节点间数据传输记录保存
	 */
	public static final com.yunat.ccms.jooq.tables.TwfLogJobData TWF_LOG_JOB_DATA = com.yunat.ccms.jooq.tables.TwfLogJobData.TWF_LOG_JOB_DATA;

	/**
	 * 流程执行中间表列表
	 */
	public static final com.yunat.ccms.jooq.tables.TwfLogNodeMids TWF_LOG_NODE_MIDS = com.yunat.ccms.jooq.tables.TwfLogNodeMids.TWF_LOG_NODE_MIDS;

	/**
	 * 流程执行子任务表
	 */
	public static final com.yunat.ccms.jooq.tables.TwfLogSubjob TWF_LOG_SUBJOB = com.yunat.ccms.jooq.tables.TwfLogSubjob.TWF_LOG_SUBJOB;

	/**
	 * 保存流程的节点信息
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNode TWF_NODE = com.yunat.ccms.jooq.tables.TwfNode.TWF_NODE;

	/**
	 * 优惠券节点配置
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeCoupon TWF_NODE_COUPON = com.yunat.ccms.jooq.tables.TwfNodeCoupon.TWF_NODE_COUPON;

	/**
	 * The table ccms.twf_node_evaluate
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeEvaluate TWF_NODE_EVALUATE = com.yunat.ccms.jooq.tables.TwfNodeEvaluate.TWF_NODE_EVALUATE;

	/**
	 * The table ccms.twf_node_evaluate_customer_detail
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeEvaluateCustomerDetail TWF_NODE_EVALUATE_CUSTOMER_DETAIL = com.yunat.ccms.jooq.tables.TwfNodeEvaluateCustomerDetail.TWF_NODE_EVALUATE_CUSTOMER_DETAIL;

	/**
	 * The table ccms.twf_node_evaluate_order_detail
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeEvaluateOrderDetail TWF_NODE_EVALUATE_ORDER_DETAIL = com.yunat.ccms.jooq.tables.TwfNodeEvaluateOrderDetail.TWF_NODE_EVALUATE_ORDER_DETAIL;

	/**
	 * 评估节点_商品明细
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeEvaluateProductDetail TWF_NODE_EVALUATE_PRODUCT_DETAIL = com.yunat.ccms.jooq.tables.TwfNodeEvaluateProductDetail.TWF_NODE_EVALUATE_PRODUCT_DETAIL;

	/**
	 * 查询节点
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeQuery TWF_NODE_QUERY = com.yunat.ccms.jooq.tables.TwfNodeQuery.TWF_NODE_QUERY;

	/**
	 * 已定义的查询条件（来自于用户界面）
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeQueryCriteria TWF_NODE_QUERY_CRITERIA = com.yunat.ccms.jooq.tables.TwfNodeQueryCriteria.TWF_NODE_QUERY_CRITERIA;

	/**
	 * 已定义查询（保存界面定义的查询）
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeQueryDefined TWF_NODE_QUERY_DEFINED = com.yunat.ccms.jooq.tables.TwfNodeQueryDefined.TWF_NODE_QUERY_DEFINED;

	/**
	 * 节点重试表
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeRetry TWF_NODE_RETRY = com.yunat.ccms.jooq.tables.TwfNodeRetry.TWF_NODE_RETRY;

	/**
	 * 短信节点
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeSms TWF_NODE_SMS = com.yunat.ccms.jooq.tables.TwfNodeSms.TWF_NODE_SMS;

	/**
	 * 短信节点执行后生成数据
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeSmsExecutionRecord TWF_NODE_SMS_EXECUTION_RECORD = com.yunat.ccms.jooq.tables.TwfNodeSmsExecutionRecord.TWF_NODE_SMS_EXECUTION_RECORD;

	/**
	 * 短信节点生成抽样数据
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeSmsSampleRecord TWF_NODE_SMS_SAMPLE_RECORD = com.yunat.ccms.jooq.tables.TwfNodeSmsSampleRecord.TWF_NODE_SMS_SAMPLE_RECORD;

	/**
	 * 目标组节点
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeTarget TWF_NODE_TARGET = com.yunat.ccms.jooq.tables.TwfNodeTarget.TWF_NODE_TARGET;

	/**
	 * 时间节点的配置信息
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeTime TWF_NODE_TIME = com.yunat.ccms.jooq.tables.TwfNodeTime.TWF_NODE_TIME;

	/**
	 * 节点类型配置表
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeType TWF_NODE_TYPE = com.yunat.ccms.jooq.tables.TwfNodeType.TWF_NODE_TYPE;

	/**
	 * 节点类型分组
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeTypeGroup TWF_NODE_TYPE_GROUP = com.yunat.ccms.jooq.tables.TwfNodeTypeGroup.TWF_NODE_TYPE_GROUP;

	/**
	 * The table ccms.twf_node_type_mid2_toolbar
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeTypeMid2Toolbar TWF_NODE_TYPE_MID2_TOOLBAR = com.yunat.ccms.jooq.tables.TwfNodeTypeMid2Toolbar.TWF_NODE_TYPE_MID2_TOOLBAR;

	/**
	 * 等待节点配置信息表
	 */
	public static final com.yunat.ccms.jooq.tables.TwfNodeWait TWF_NODE_WAIT = com.yunat.ccms.jooq.tables.TwfNodeWait.TWF_NODE_WAIT;

	/**
	 * 流程信息表
	 */
	public static final com.yunat.ccms.jooq.tables.TwfWorkflow TWF_WORKFLOW = com.yunat.ccms.jooq.tables.TwfWorkflow.TWF_WORKFLOW;

	/**
	 * “流程类别”所对应的“节点类型分组”
	 */
	public static final com.yunat.ccms.jooq.tables.TwfWorkflowNodeGroup TWF_WORKFLOW_NODE_GROUP = com.yunat.ccms.jooq.tables.TwfWorkflowNodeGroup.TWF_WORKFLOW_NODE_GROUP;

	/**
	 * EDM黑名单表
	 */
	public static final com.yunat.ccms.jooq.tables.TwEmailBlacklist TW_EMAIL_BLACKLIST = com.yunat.ccms.jooq.tables.TwEmailBlacklist.TW_EMAIL_BLACKLIST;

	/**
	 * EDM红名单表
	 */
	public static final com.yunat.ccms.jooq.tables.TwEmailRedlist TW_EMAIL_REDLIST = com.yunat.ccms.jooq.tables.TwEmailRedlist.TW_EMAIL_REDLIST;

	/**
	 * 会员黑名单表
	 */
	public static final com.yunat.ccms.jooq.tables.TwMemberBlacklist TW_MEMBER_BLACKLIST = com.yunat.ccms.jooq.tables.TwMemberBlacklist.TW_MEMBER_BLACKLIST;

	/**
	 * 短信手机黑名单表
	 */
	public static final com.yunat.ccms.jooq.tables.TwMobileBlacklist TW_MOBILE_BLACKLIST = com.yunat.ccms.jooq.tables.TwMobileBlacklist.TW_MOBILE_BLACKLIST;

	/**
	 * 手机短信红名单表
	 */
	public static final com.yunat.ccms.jooq.tables.TwMobileRedlist TW_MOBILE_REDLIST = com.yunat.ccms.jooq.tables.TwMobileRedlist.TW_MOBILE_REDLIST;

	/**
	 * 客户统一信息表
	 */
	public static final com.yunat.ccms.jooq.tables.UniCustomer UNI_CUSTOMER = com.yunat.ccms.jooq.tables.UniCustomer.UNI_CUSTOMER;

	/**
	 * 客户各平台ID关系表
	 */
	public static final com.yunat.ccms.jooq.tables.UniCustomerPlat UNI_CUSTOMER_PLAT = com.yunat.ccms.jooq.tables.UniCustomerPlat.UNI_CUSTOMER_PLAT;

	/**
	 * 客户来源平台信息
	 */
	public static final com.yunat.ccms.jooq.tables.UniPlat UNI_PLAT = com.yunat.ccms.jooq.tables.UniPlat.UNI_PLAT;

	/**
	 * VIEW
	 */
	public static final com.yunat.ccms.jooq.tables.VmTaobaoOrder VM_TAOBAO_ORDER = com.yunat.ccms.jooq.tables.VmTaobaoOrder.VM_TAOBAO_ORDER;

	/**
	 * VIEW
	 */
	public static final com.yunat.ccms.jooq.tables.VwTaobaoCustomer VW_TAOBAO_CUSTOMER = com.yunat.ccms.jooq.tables.VwTaobaoCustomer.VW_TAOBAO_CUSTOMER;

	/**
	 * No instances
	 */
	private Tables() {}
}
