/**
 * This class is generated by jOOQ
 */
package com.yunat.ccms.jooq.routines;

/**
 * This class is generated by jOOQ.
 *
 * 统一客户信息被手工修改时过程
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.3"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class ProcUnifyModifyCustomer extends org.jooq.impl.AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = 1485127301;


	/**
	 * The procedure parameter <code>ccms.proc_unify_modify_customer.p_customerno</code>
	 */
	public static final org.jooq.Parameter<java.lang.String> P_CUSTOMERNO = createParameter("p_customerno", org.jooq.impl.SQLDataType.VARCHAR);

	/**
	 * The procedure parameter <code>ccms.proc_unify_modify_customer.p_full_name</code>
	 */
	public static final org.jooq.Parameter<java.lang.String> P_FULL_NAME = createParameter("p_full_name", org.jooq.impl.SQLDataType.VARCHAR);

	/**
	 * The procedure parameter <code>ccms.proc_unify_modify_customer.p_sex</code>
	 */
	public static final org.jooq.Parameter<java.lang.String> P_SEX = createParameter("p_sex", org.jooq.impl.SQLDataType.CHAR);

	/**
	 * The procedure parameter <code>ccms.proc_unify_modify_customer.p_job</code>
	 */
	public static final org.jooq.Parameter<java.lang.String> P_JOB = createParameter("p_job", org.jooq.impl.SQLDataType.VARCHAR);

	/**
	 * The procedure parameter <code>ccms.proc_unify_modify_customer.p_birth_year</code>
	 */
	public static final org.jooq.Parameter<java.lang.Short> P_BIRTH_YEAR = createParameter("p_birth_year", org.jooq.impl.SQLDataType.SMALLINT);

	/**
	 * The procedure parameter <code>ccms.proc_unify_modify_customer.p_birthday</code>
	 */
	public static final org.jooq.Parameter<java.sql.Date> P_BIRTHDAY = createParameter("p_birthday", org.jooq.impl.SQLDataType.DATE);

	/**
	 * The procedure parameter <code>ccms.proc_unify_modify_customer.p_email</code>
	 */
	public static final org.jooq.Parameter<java.lang.String> P_EMAIL = createParameter("p_email", org.jooq.impl.SQLDataType.VARCHAR);

	/**
	 * The procedure parameter <code>ccms.proc_unify_modify_customer.p_mobile</code>
	 */
	public static final org.jooq.Parameter<java.lang.String> P_MOBILE = createParameter("p_mobile", org.jooq.impl.SQLDataType.VARCHAR);

	/**
	 * The procedure parameter <code>ccms.proc_unify_modify_customer.p_phone</code>
	 */
	public static final org.jooq.Parameter<java.lang.String> P_PHONE = createParameter("p_phone", org.jooq.impl.SQLDataType.VARCHAR);

	/**
	 * The procedure parameter <code>ccms.proc_unify_modify_customer.p_zip</code>
	 */
	public static final org.jooq.Parameter<java.lang.String> P_ZIP = createParameter("p_zip", org.jooq.impl.SQLDataType.VARCHAR);

	/**
	 * The procedure parameter <code>ccms.proc_unify_modify_customer.p_country</code>
	 */
	public static final org.jooq.Parameter<java.lang.String> P_COUNTRY = createParameter("p_country", org.jooq.impl.SQLDataType.VARCHAR);

	/**
	 * The procedure parameter <code>ccms.proc_unify_modify_customer.p_state</code>
	 */
	public static final org.jooq.Parameter<java.lang.String> P_STATE = createParameter("p_state", org.jooq.impl.SQLDataType.VARCHAR);

	/**
	 * The procedure parameter <code>ccms.proc_unify_modify_customer.p_city</code>
	 */
	public static final org.jooq.Parameter<java.lang.String> P_CITY = createParameter("p_city", org.jooq.impl.SQLDataType.VARCHAR);

	/**
	 * The procedure parameter <code>ccms.proc_unify_modify_customer.p_district</code>
	 */
	public static final org.jooq.Parameter<java.lang.String> P_DISTRICT = createParameter("p_district", org.jooq.impl.SQLDataType.VARCHAR);

	/**
	 * The procedure parameter <code>ccms.proc_unify_modify_customer.p_address</code>
	 */
	public static final org.jooq.Parameter<java.lang.String> P_ADDRESS = createParameter("p_address", org.jooq.impl.SQLDataType.VARCHAR);

	/**
	 * The procedure parameter <code>ccms.proc_unify_modify_customer.p_changed</code>
	 */
	public static final org.jooq.Parameter<java.sql.Timestamp> P_CHANGED = createParameter("p_changed", org.jooq.impl.SQLDataType.TIMESTAMP);

	/**
	 * Create a new routine call instance
	 */
	public ProcUnifyModifyCustomer() {
		super("proc_unify_modify_customer", com.yunat.ccms.jooq.Ccms.CCMS);

		addInParameter(P_CUSTOMERNO);
		addInParameter(P_FULL_NAME);
		addInParameter(P_SEX);
		addInParameter(P_JOB);
		addInParameter(P_BIRTH_YEAR);
		addInParameter(P_BIRTHDAY);
		addInParameter(P_EMAIL);
		addInParameter(P_MOBILE);
		addInParameter(P_PHONE);
		addInParameter(P_ZIP);
		addInParameter(P_COUNTRY);
		addInParameter(P_STATE);
		addInParameter(P_CITY);
		addInParameter(P_DISTRICT);
		addInParameter(P_ADDRESS);
		addInParameter(P_CHANGED);
	}

	/**
	 * Set the <code>p_customerno</code> parameter IN value to the routine
	 */
	public void setPCustomerno(java.lang.String value) {
		setValue(com.yunat.ccms.jooq.routines.ProcUnifyModifyCustomer.P_CUSTOMERNO, value);
	}

	/**
	 * Set the <code>p_full_name</code> parameter IN value to the routine
	 */
	public void setPFullName(java.lang.String value) {
		setValue(com.yunat.ccms.jooq.routines.ProcUnifyModifyCustomer.P_FULL_NAME, value);
	}

	/**
	 * Set the <code>p_sex</code> parameter IN value to the routine
	 */
	public void setPSex(java.lang.String value) {
		setValue(com.yunat.ccms.jooq.routines.ProcUnifyModifyCustomer.P_SEX, value);
	}

	/**
	 * Set the <code>p_job</code> parameter IN value to the routine
	 */
	public void setPJob(java.lang.String value) {
		setValue(com.yunat.ccms.jooq.routines.ProcUnifyModifyCustomer.P_JOB, value);
	}

	/**
	 * Set the <code>p_birth_year</code> parameter IN value to the routine
	 */
	public void setPBirthYear(java.lang.Short value) {
		setValue(com.yunat.ccms.jooq.routines.ProcUnifyModifyCustomer.P_BIRTH_YEAR, value);
	}

	/**
	 * Set the <code>p_birthday</code> parameter IN value to the routine
	 */
	public void setPBirthday(java.sql.Date value) {
		setValue(com.yunat.ccms.jooq.routines.ProcUnifyModifyCustomer.P_BIRTHDAY, value);
	}

	/**
	 * Set the <code>p_email</code> parameter IN value to the routine
	 */
	public void setPEmail(java.lang.String value) {
		setValue(com.yunat.ccms.jooq.routines.ProcUnifyModifyCustomer.P_EMAIL, value);
	}

	/**
	 * Set the <code>p_mobile</code> parameter IN value to the routine
	 */
	public void setPMobile(java.lang.String value) {
		setValue(com.yunat.ccms.jooq.routines.ProcUnifyModifyCustomer.P_MOBILE, value);
	}

	/**
	 * Set the <code>p_phone</code> parameter IN value to the routine
	 */
	public void setPPhone(java.lang.String value) {
		setValue(com.yunat.ccms.jooq.routines.ProcUnifyModifyCustomer.P_PHONE, value);
	}

	/**
	 * Set the <code>p_zip</code> parameter IN value to the routine
	 */
	public void setPZip(java.lang.String value) {
		setValue(com.yunat.ccms.jooq.routines.ProcUnifyModifyCustomer.P_ZIP, value);
	}

	/**
	 * Set the <code>p_country</code> parameter IN value to the routine
	 */
	public void setPCountry(java.lang.String value) {
		setValue(com.yunat.ccms.jooq.routines.ProcUnifyModifyCustomer.P_COUNTRY, value);
	}

	/**
	 * Set the <code>p_state</code> parameter IN value to the routine
	 */
	public void setPState(java.lang.String value) {
		setValue(com.yunat.ccms.jooq.routines.ProcUnifyModifyCustomer.P_STATE, value);
	}

	/**
	 * Set the <code>p_city</code> parameter IN value to the routine
	 */
	public void setPCity(java.lang.String value) {
		setValue(com.yunat.ccms.jooq.routines.ProcUnifyModifyCustomer.P_CITY, value);
	}

	/**
	 * Set the <code>p_district</code> parameter IN value to the routine
	 */
	public void setPDistrict(java.lang.String value) {
		setValue(com.yunat.ccms.jooq.routines.ProcUnifyModifyCustomer.P_DISTRICT, value);
	}

	/**
	 * Set the <code>p_address</code> parameter IN value to the routine
	 */
	public void setPAddress(java.lang.String value) {
		setValue(com.yunat.ccms.jooq.routines.ProcUnifyModifyCustomer.P_ADDRESS, value);
	}

	/**
	 * Set the <code>p_changed</code> parameter IN value to the routine
	 */
	public void setPChanged(java.sql.Timestamp value) {
		setValue(com.yunat.ccms.jooq.routines.ProcUnifyModifyCustomer.P_CHANGED, value);
	}
}
